@echo off

rem Find SDK_ROOT by searching backwards from cwd for SDKs
set SDK_ROOT=%~p0
:sdkloop
if exist "%SDK_ROOT%\Source" goto :havesdkpath
set SDK_ROOT=%SDK_ROOT%..\
goto :sdkloop

:havesdkpath


call "%SDK_ROOT%\Tools\PhysXMetaDataGenerator\get_common_settings.bat"

set SRCPATH=PxSnippetExtensionAPI.h

if not defined TARGETDIR (set TARGETDIR="%SDK_ROOT%\Snippets\SnippetExtension\src\PhysXMetaData")
set TARGETNAME=PxSnippetExtension

set AUTOFILENAME1=%TARGETDIR%\include\%TARGETNAME%AutoGeneratedMetaDataObjectNames.h
set AUTOFILENAME2=%TARGETDIR%\include\%TARGETNAME%AutoGeneratedMetaDataObjects.h
set AUTOFILENAME3=%TARGETDIR%\src\%TARGETNAME%AutoGeneratedMetaDataObjects.cpp

echo. 2>%AUTOFILENAME1%
echo. 2>%AUTOFILENAME2%
echo. 2>%AUTOFILENAME3%


set INCLUDES=%INCLUDES% -I"%SDK_ROOT%/Snippets/SnippetExtension/include"
set INCLUDES=%INCLUDES% -I"%SDK_ROOT%/Snippets/SnippetExtension/src"

