vs_3_0
// cgc version 2.2.0017, build date Jan 29 2010
// command line args: -profile vs_3_0 -I../include -DGLSL_COMPILER -DPASS_DEFERRED -DNO_SUPPORT_DDX_DDY
// source file: tablet_buttons.cg
//vendor NVIDIA Corporation
//version 2.2.0.17
//profile vs_3_0
//program vmain
//var float4 localSpacePosition : $vin.POSITION0 : ATTR0 : 0 : 1
//var float4 vmain.screenSpacePosition : $vout.POSITION : ATTR0 : -1 : 1
dcl_position o0
dcl_position0 v0
mov o0, v0
