# Makefile generated by XPJ for android16
-include Makefile.custom
ProjectName = Samples
Samples_cppfiles   += ./../../SampleHelloWorld/SampleHelloWorld.cpp
Samples_cppfiles   += ./../../SampleBridges/SampleBridges.cpp
Samples_cppfiles   += ./../../SampleBridges/SampleBridgesCCT.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterClothCameraController.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterClothFlag.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterClothJump.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_CCT.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_ClothController.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_FilterShader.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_Main.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_Platform.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_PlatformBuilder.cpp
Samples_cppfiles   += ./../../SampleCharacterCloth/SampleCharacterCloth_TerrainBuilder.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicleDebugRender.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicleTerrain.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_CameraController.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_ControlInputs.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_GameLogic.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_SceneQuery.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_VehicleController.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_VehicleCooking.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_VehicleManager.cpp
Samples_cppfiles   += ./../../SampleVehicle/SampleVehicle_WheelQueryResults.cpp
Samples_cppfiles   += ./../../SampleParticles/SampleParticles.cpp
Samples_cppfiles   += ./../../SampleSubmarine/Crab.cpp
Samples_cppfiles   += ./../../SampleSubmarine/SampleSubmarine.cpp
Samples_cppfiles   += ./../../SampleNorthPole/SampleNorthPole.cpp
Samples_cppfiles   += ./../../SampleNorthPole/SampleNorthPoleBuilder.cpp
Samples_cppfiles   += ./../../SampleNorthPole/SampleNorthPoleCameraController.cpp
Samples_cppfiles   += ./../../SampleNorthPole/SampleNorthPoleCCT.cpp
Samples_cppfiles   += ./../../SampleNorthPole/SampleNorthPoleDynamics.cpp
Samples_cppfiles   += ./../../SampleNorthPole/SampleNorthPoleFilterShader.cpp
Samples_cppfiles   += ./../../SampleCustomGravity/Planet.cpp
Samples_cppfiles   += ./../../SampleCustomGravity/SampleCustomGravity.cpp
Samples_cppfiles   += ./../../SampleCustomGravity/SampleCustomGravityBuilder.cpp
Samples_cppfiles   += ./../../SampleCustomGravity/SampleCustomGravityCameraController.cpp
Samples_cppfiles   += ./../../SampleCustomGravity/SampleCustomGravityFilterShader.cpp
Samples_cppfiles   += ./../../SampleCustomGravity/SampleCustomGravity_CCT.cpp
Samples_cppfiles   += ./../../SampleLargeWorld/ChunkLoader.cpp
Samples_cppfiles   += ./../../SampleLargeWorld/MeshBuilder.cpp
Samples_cppfiles   += ./../../SampleLargeWorld/SampleLargeWorld.cpp
Samples_cppfiles   += ./../../SampleLargeWorld/SampleLargeWorldCCT.cpp
Samples_cppfiles   += ./../../SampleCCTSharedCode/KinematicPlatform.cpp
Samples_cppfiles   += ./../../SampleCCTSharedCode/SampleCCTActor.cpp
Samples_cppfiles   += ./../../SampleCCTSharedCode/SampleCCTCameraController.cpp
Samples_cppfiles   += ./../../SampleCCTSharedCode/SampleCCTJump.cpp

Samples_cpp_debug_dep    = $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(Samples_cppfiles)))))
Samples_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(Samples_ccfiles)))))
Samples_c_debug_dep      = $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(Samples_cfiles)))))
Samples_debug_dep      = $(Samples_cpp_debug_dep) $(Samples_cc_debug_dep) $(Samples_c_debug_dep)
-include $(Samples_debug_dep)
Samples_cpp_checked_dep    = $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(Samples_cppfiles)))))
Samples_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(Samples_ccfiles)))))
Samples_c_checked_dep      = $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(Samples_cfiles)))))
Samples_checked_dep      = $(Samples_cpp_checked_dep) $(Samples_cc_checked_dep) $(Samples_c_checked_dep)
-include $(Samples_checked_dep)
Samples_cpp_profile_dep    = $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(Samples_cppfiles)))))
Samples_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(Samples_ccfiles)))))
Samples_c_profile_dep      = $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(Samples_cfiles)))))
Samples_profile_dep      = $(Samples_cpp_profile_dep) $(Samples_cc_profile_dep) $(Samples_c_profile_dep)
-include $(Samples_profile_dep)
Samples_cpp_release_dep    = $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(Samples_cppfiles)))))
Samples_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(Samples_ccfiles)))))
Samples_c_release_dep      = $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(Samples_cfiles)))))
Samples_release_dep      = $(Samples_cpp_release_dep) $(Samples_cc_release_dep) $(Samples_c_release_dep)
-include $(Samples_release_dep)
Samples_debug_hpaths    := 
Samples_debug_hpaths    += ./../../SampleBase
Samples_debug_hpaths    += ./../../PxToolkit/include
Samples_debug_hpaths    += ./../../SampleFramework/framework/include
Samples_debug_hpaths    += ./../../SampleFramework/renderer/include
Samples_debug_hpaths    += ./../../SampleFramework/platform/include
Samples_debug_hpaths    += ./../../../Include
Samples_debug_hpaths    += ./../../../Source/foundation/include
Samples_debug_hpaths    += ./../../../Source/Common/src
Samples_debug_hpaths    += ./../../../Source/GeomUtils/headers
Samples_debug_hpaths    += ./../../../Source/GeomUtils/include
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/contact
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/common
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/convex
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/distance
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/gjk
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/intersection
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/mesh
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/Ice
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/hf
Samples_debug_hpaths    += ./../../../Source/GeomUtils/src/pcm
Samples_debug_hpaths    += ./../../../Include/foundation
Samples_debug_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
Samples_debug_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
Samples_debug_hpaths    += ./../../../Include/common
Samples_debug_hpaths    += ./../../SampleCCTSharedCode
Samples_debug_hpaths    += ./../../../Source/PhysXVehicle/src
Samples_debug_lpaths    := 
Samples_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
Samples_debug_lpaths    += ./../../../Lib/android16
Samples_debug_lpaths    += ./../../lib/android16
Samples_debug_lpaths    += ./../../SampleFramework/platform/lib/android16
Samples_debug_lpaths    += ./../../SampleFramework/renderer/lib/android16
Samples_debug_lpaths    += ./../../SampleFramework/framework/lib/android16
Samples_debug_lpaths    += ./../../PxToolkit/lib/android16
Samples_debug_lpaths    += ./../../../externals/mojoshader/1067/lib/android16
Samples_debug_lpaths    += ./../../PxToolkit/lib/android16
Samples_debug_lpaths    += ./../../lib/android16
Samples_debug_defines   := $(Samples_custom_defines)
Samples_debug_defines   += ANDROID
Samples_debug_defines   += GLES2
Samples_debug_defines   += __ARM_ARCH_5__
Samples_debug_defines   += __ARM_ARCH_5T__
Samples_debug_defines   += __ARM_ARCH_5E__
Samples_debug_defines   += __ARM_ARCH_5TE__
Samples_debug_defines   += _DEBUG
Samples_debug_defines   += PX_DEBUG
Samples_debug_defines   += PX_CHECKED
Samples_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
Samples_debug_defines   += PX_NVTX
Samples_debug_defines   += PHYSX_PROFILE_SDK
Samples_debug_libraries := 
Samples_debug_libraries += MojoShaderDEBUG
Samples_debug_libraries += PxToolkitDEBUG
Samples_debug_libraries += SampleBaseDEBUG
Samples_debug_libraries += log
Samples_debug_libraries += android
Samples_debug_libraries += EGL
Samples_debug_libraries += GLESv2
Samples_debug_libraries += supc++
Samples_debug_libraries += gnustl_static
Samples_debug_libraries += nvToolsExt
Samples_debug_libraries += PxToolkitDEBUG
Samples_debug_libraries += SampleBaseDEBUG
Samples_debug_libraries += SampleFramework-MTDEBUG
Samples_debug_libraries += SampleRenderer-MTDEBUG
Samples_debug_libraries += SamplePlatform-MTDEBUG
Samples_debug_libraries += PhysX3CommonDEBUG
Samples_debug_libraries += PhysX3DEBUG
Samples_debug_libraries += PhysX3VehicleDEBUG
Samples_debug_libraries += PhysX3CookingDEBUG
Samples_debug_libraries += PhysX3ExtensionsDEBUG
Samples_debug_libraries += PhysX3CharacterKinematicDEBUG
Samples_debug_common_cflags	:= $(Samples_custom_cflags)
Samples_debug_common_cflags    += -MMD
Samples_debug_common_cflags    += $(addprefix -D, $(Samples_debug_defines))
Samples_debug_common_cflags    += $(addprefix -I, $(Samples_debug_hpaths))
Samples_debug_common_cflags  += -Werror
Samples_debug_common_cflags  += -fpic -fno-exceptions
Samples_debug_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_debug_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
Samples_debug_common_cflags  += -g3 -gdwarf-2
Samples_debug_cflags	:= $(Samples_debug_common_cflags)
Samples_debug_cppflags	:= $(Samples_debug_common_cflags)
Samples_debug_cppflags  += -fno-rtti
Samples_debug_lflags    := $(Samples_custom_lflags)
Samples_debug_lflags    += $(addprefix -L, $(Samples_debug_lpaths))
Samples_debug_lflags    += -Wl,--start-group $(addprefix -l, $(Samples_debug_libraries)) -Wl,--end-group
Samples_debug_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_debug_lflags  += -Wl,--no-undefined
Samples_debug_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
Samples_debug_objsdir  = $(OBJS_DIR)/Samples_debug
Samples_debug_cpp_o    = $(addprefix $(Samples_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(Samples_cppfiles)))))
Samples_debug_cc_o    = $(addprefix $(Samples_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(Samples_ccfiles)))))
Samples_debug_c_o      = $(addprefix $(Samples_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(Samples_cfiles)))))
Samples_debug_obj      = $(Samples_debug_cpp_o) $(Samples_debug_cc_o) $(Samples_debug_c_o)
Samples_debug_bin      := ./../../lib/android16/libSamplesDEBUG.so

clean_Samples_debug: 
	@$(ECHO) clean Samples debug
	@$(RMDIR) $(Samples_debug_objsdir)
	@$(RMDIR) $(Samples_debug_bin)
	@$(RMDIR) $(DEPSDIR)/Samples/debug

build_Samples_debug: postbuild_Samples_debug
postbuild_Samples_debug: mainbuild_Samples_debug
mainbuild_Samples_debug: prebuild_Samples_debug $(Samples_debug_bin)
prebuild_Samples_debug:

$(Samples_debug_bin): $(Samples_debug_obj) build_MojoShader_debug build_PxToolkit_debug build_SampleBase_debug 
	mkdir -p `dirname ./../../lib/android16/libSamplesDEBUG.so`
	$(CXX) -shared $(Samples_debug_obj) $(Samples_debug_lflags) -lc -o $@ 
	$(ECHO) building $@ complete!

Samples_debug_DEPDIR = $(dir $(@))/$(*F)
$(Samples_debug_cpp_o): $(Samples_debug_objsdir)/%.o:
	$(ECHO) Samples: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cppfiles))))))
	cp $(Samples_debug_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  rm -f $(Samples_debug_DEPDIR).d

$(Samples_debug_cc_o): $(Samples_debug_objsdir)/%.o:
	$(ECHO) Samples: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_ccfiles))))))
	cp $(Samples_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_ccfiles))))).debug.P; \
	  rm -f $(Samples_debug_DEPDIR).d

$(Samples_debug_c_o): $(Samples_debug_objsdir)/%.o:
	$(ECHO) Samples: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(Samples_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cfiles))))))
	cp $(Samples_debug_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_debug_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  rm -f $(Samples_debug_DEPDIR).d

Samples_checked_hpaths    := 
Samples_checked_hpaths    += ./../../SampleBase
Samples_checked_hpaths    += ./../../PxToolkit/include
Samples_checked_hpaths    += ./../../SampleFramework/framework/include
Samples_checked_hpaths    += ./../../SampleFramework/renderer/include
Samples_checked_hpaths    += ./../../SampleFramework/platform/include
Samples_checked_hpaths    += ./../../../Include
Samples_checked_hpaths    += ./../../../Source/foundation/include
Samples_checked_hpaths    += ./../../../Source/Common/src
Samples_checked_hpaths    += ./../../../Source/GeomUtils/headers
Samples_checked_hpaths    += ./../../../Source/GeomUtils/include
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/contact
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/common
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/convex
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/distance
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/gjk
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/intersection
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/mesh
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/Ice
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/hf
Samples_checked_hpaths    += ./../../../Source/GeomUtils/src/pcm
Samples_checked_hpaths    += ./../../../Include/foundation
Samples_checked_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
Samples_checked_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
Samples_checked_hpaths    += ./../../../Include/common
Samples_checked_hpaths    += ./../../SampleCCTSharedCode
Samples_checked_hpaths    += ./../../../Source/PhysXVehicle/src
Samples_checked_lpaths    := 
Samples_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
Samples_checked_lpaths    += ./../../../Lib/android16
Samples_checked_lpaths    += ./../../lib/android16
Samples_checked_lpaths    += ./../../SampleFramework/platform/lib/android16
Samples_checked_lpaths    += ./../../SampleFramework/renderer/lib/android16
Samples_checked_lpaths    += ./../../SampleFramework/framework/lib/android16
Samples_checked_lpaths    += ./../../PxToolkit/lib/android16
Samples_checked_lpaths    += ./../../../externals/mojoshader/1067/lib/android16
Samples_checked_lpaths    += ./../../PxToolkit/lib/android16
Samples_checked_lpaths    += ./../../lib/android16
Samples_checked_defines   := $(Samples_custom_defines)
Samples_checked_defines   += ANDROID
Samples_checked_defines   += GLES2
Samples_checked_defines   += __ARM_ARCH_5__
Samples_checked_defines   += __ARM_ARCH_5T__
Samples_checked_defines   += __ARM_ARCH_5E__
Samples_checked_defines   += __ARM_ARCH_5TE__
Samples_checked_defines   += NDEBUG
Samples_checked_defines   += PX_CHECKED
Samples_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
Samples_checked_defines   += PX_NVTX
Samples_checked_defines   += PHYSX_PROFILE_SDK
Samples_checked_libraries := 
Samples_checked_libraries += MojoShaderCHECKED
Samples_checked_libraries += PxToolkitCHECKED
Samples_checked_libraries += SampleBaseCHECKED
Samples_checked_libraries += log
Samples_checked_libraries += android
Samples_checked_libraries += EGL
Samples_checked_libraries += GLESv2
Samples_checked_libraries += supc++
Samples_checked_libraries += gnustl_static
Samples_checked_libraries += nvToolsExt
Samples_checked_libraries += PxToolkitCHECKED
Samples_checked_libraries += SampleBaseCHECKED
Samples_checked_libraries += SampleFramework-MTCHECKED
Samples_checked_libraries += SampleRenderer-MTCHECKED
Samples_checked_libraries += SamplePlatform-MTCHECKED
Samples_checked_libraries += PhysX3CommonCHECKED
Samples_checked_libraries += PhysX3CHECKED
Samples_checked_libraries += PhysX3VehicleCHECKED
Samples_checked_libraries += PhysX3CookingCHECKED
Samples_checked_libraries += PhysX3ExtensionsCHECKED
Samples_checked_libraries += PhysX3CharacterKinematicCHECKED
Samples_checked_common_cflags	:= $(Samples_custom_cflags)
Samples_checked_common_cflags    += -MMD
Samples_checked_common_cflags    += $(addprefix -D, $(Samples_checked_defines))
Samples_checked_common_cflags    += $(addprefix -I, $(Samples_checked_hpaths))
Samples_checked_common_cflags  += -Werror
Samples_checked_common_cflags  += -fpic -fno-exceptions
Samples_checked_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_checked_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
Samples_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
Samples_checked_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
Samples_checked_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
Samples_checked_cflags	:= $(Samples_checked_common_cflags)
Samples_checked_cppflags	:= $(Samples_checked_common_cflags)
Samples_checked_cppflags  += -fno-rtti
Samples_checked_lflags    := $(Samples_custom_lflags)
Samples_checked_lflags    += $(addprefix -L, $(Samples_checked_lpaths))
Samples_checked_lflags    += -Wl,--start-group $(addprefix -l, $(Samples_checked_libraries)) -Wl,--end-group
Samples_checked_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_checked_lflags  += -Wl,--no-undefined
Samples_checked_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
Samples_checked_objsdir  = $(OBJS_DIR)/Samples_checked
Samples_checked_cpp_o    = $(addprefix $(Samples_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(Samples_cppfiles)))))
Samples_checked_cc_o    = $(addprefix $(Samples_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(Samples_ccfiles)))))
Samples_checked_c_o      = $(addprefix $(Samples_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(Samples_cfiles)))))
Samples_checked_obj      = $(Samples_checked_cpp_o) $(Samples_checked_cc_o) $(Samples_checked_c_o)
Samples_checked_bin      := ./../../lib/android16/libSamplesCHECKED.so

clean_Samples_checked: 
	@$(ECHO) clean Samples checked
	@$(RMDIR) $(Samples_checked_objsdir)
	@$(RMDIR) $(Samples_checked_bin)
	@$(RMDIR) $(DEPSDIR)/Samples/checked

build_Samples_checked: postbuild_Samples_checked
postbuild_Samples_checked: mainbuild_Samples_checked
mainbuild_Samples_checked: prebuild_Samples_checked $(Samples_checked_bin)
prebuild_Samples_checked:

$(Samples_checked_bin): $(Samples_checked_obj) build_MojoShader_checked build_PxToolkit_checked build_SampleBase_checked 
	mkdir -p `dirname ./../../lib/android16/libSamplesCHECKED.so`
	$(CXX) -shared $(Samples_checked_obj) $(Samples_checked_lflags) -lc -o $@ 
	$(ECHO) building $@ complete!

Samples_checked_DEPDIR = $(dir $(@))/$(*F)
$(Samples_checked_cpp_o): $(Samples_checked_objsdir)/%.o:
	$(ECHO) Samples: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cppfiles))))))
	cp $(Samples_checked_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  rm -f $(Samples_checked_DEPDIR).d

$(Samples_checked_cc_o): $(Samples_checked_objsdir)/%.o:
	$(ECHO) Samples: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_ccfiles))))))
	cp $(Samples_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_ccfiles))))).checked.P; \
	  rm -f $(Samples_checked_DEPDIR).d

$(Samples_checked_c_o): $(Samples_checked_objsdir)/%.o:
	$(ECHO) Samples: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(Samples_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cfiles))))))
	cp $(Samples_checked_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_checked_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  rm -f $(Samples_checked_DEPDIR).d

Samples_profile_hpaths    := 
Samples_profile_hpaths    += ./../../SampleBase
Samples_profile_hpaths    += ./../../PxToolkit/include
Samples_profile_hpaths    += ./../../SampleFramework/framework/include
Samples_profile_hpaths    += ./../../SampleFramework/renderer/include
Samples_profile_hpaths    += ./../../SampleFramework/platform/include
Samples_profile_hpaths    += ./../../../Include
Samples_profile_hpaths    += ./../../../Source/foundation/include
Samples_profile_hpaths    += ./../../../Source/Common/src
Samples_profile_hpaths    += ./../../../Source/GeomUtils/headers
Samples_profile_hpaths    += ./../../../Source/GeomUtils/include
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/contact
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/common
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/convex
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/distance
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/gjk
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/intersection
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/mesh
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/Ice
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/hf
Samples_profile_hpaths    += ./../../../Source/GeomUtils/src/pcm
Samples_profile_hpaths    += ./../../../Include/foundation
Samples_profile_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
Samples_profile_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
Samples_profile_hpaths    += ./../../../Include/common
Samples_profile_hpaths    += ./../../SampleCCTSharedCode
Samples_profile_hpaths    += ./../../../Source/PhysXVehicle/src
Samples_profile_lpaths    := 
Samples_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
Samples_profile_lpaths    += ./../../../Lib/android16
Samples_profile_lpaths    += ./../../lib/android16
Samples_profile_lpaths    += ./../../SampleFramework/platform/lib/android16
Samples_profile_lpaths    += ./../../SampleFramework/renderer/lib/android16
Samples_profile_lpaths    += ./../../SampleFramework/framework/lib/android16
Samples_profile_lpaths    += ./../../PxToolkit/lib/android16
Samples_profile_lpaths    += ./../../../externals/mojoshader/1067/lib/android16
Samples_profile_lpaths    += ./../../PxToolkit/lib/android16
Samples_profile_lpaths    += ./../../lib/android16
Samples_profile_defines   := $(Samples_custom_defines)
Samples_profile_defines   += ANDROID
Samples_profile_defines   += GLES2
Samples_profile_defines   += __ARM_ARCH_5__
Samples_profile_defines   += __ARM_ARCH_5T__
Samples_profile_defines   += __ARM_ARCH_5E__
Samples_profile_defines   += __ARM_ARCH_5TE__
Samples_profile_defines   += NDEBUG
Samples_profile_defines   += PX_PROFILE
Samples_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
Samples_profile_defines   += PX_NVTX
Samples_profile_defines   += PHYSX_PROFILE_SDK
Samples_profile_libraries := 
Samples_profile_libraries += MojoShaderPROFILE
Samples_profile_libraries += PxToolkitPROFILE
Samples_profile_libraries += SampleBasePROFILE
Samples_profile_libraries += log
Samples_profile_libraries += android
Samples_profile_libraries += EGL
Samples_profile_libraries += GLESv2
Samples_profile_libraries += supc++
Samples_profile_libraries += gnustl_static
Samples_profile_libraries += nvToolsExt
Samples_profile_libraries += PxToolkitPROFILE
Samples_profile_libraries += SampleBasePROFILE
Samples_profile_libraries += SampleFramework-MTPROFILE
Samples_profile_libraries += SampleRenderer-MTPROFILE
Samples_profile_libraries += SamplePlatform-MTPROFILE
Samples_profile_libraries += PhysX3CommonPROFILE
Samples_profile_libraries += PhysX3PROFILE
Samples_profile_libraries += PhysX3VehiclePROFILE
Samples_profile_libraries += PhysX3CookingPROFILE
Samples_profile_libraries += PhysX3ExtensionsPROFILE
Samples_profile_libraries += PhysX3CharacterKinematicPROFILE
Samples_profile_common_cflags	:= $(Samples_custom_cflags)
Samples_profile_common_cflags    += -MMD
Samples_profile_common_cflags    += $(addprefix -D, $(Samples_profile_defines))
Samples_profile_common_cflags    += $(addprefix -I, $(Samples_profile_hpaths))
Samples_profile_common_cflags  += -Werror
Samples_profile_common_cflags  += -fpic -fno-exceptions
Samples_profile_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_profile_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
Samples_profile_common_cflags  += -O3 -fno-strict-aliasing
Samples_profile_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
Samples_profile_common_cflags  += -fno-omit-frame-pointer -funswitch-loops -finline-limit=300
Samples_profile_cflags	:= $(Samples_profile_common_cflags)
Samples_profile_cppflags	:= $(Samples_profile_common_cflags)
Samples_profile_cppflags  += -fno-rtti
Samples_profile_lflags    := $(Samples_custom_lflags)
Samples_profile_lflags    += $(addprefix -L, $(Samples_profile_lpaths))
Samples_profile_lflags    += -Wl,--start-group $(addprefix -l, $(Samples_profile_libraries)) -Wl,--end-group
Samples_profile_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_profile_lflags  += -Wl,--no-undefined
Samples_profile_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
Samples_profile_objsdir  = $(OBJS_DIR)/Samples_profile
Samples_profile_cpp_o    = $(addprefix $(Samples_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(Samples_cppfiles)))))
Samples_profile_cc_o    = $(addprefix $(Samples_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(Samples_ccfiles)))))
Samples_profile_c_o      = $(addprefix $(Samples_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(Samples_cfiles)))))
Samples_profile_obj      = $(Samples_profile_cpp_o) $(Samples_profile_cc_o) $(Samples_profile_c_o)
Samples_profile_bin      := ./../../lib/android16/libSamplesPROFILE.so

clean_Samples_profile: 
	@$(ECHO) clean Samples profile
	@$(RMDIR) $(Samples_profile_objsdir)
	@$(RMDIR) $(Samples_profile_bin)
	@$(RMDIR) $(DEPSDIR)/Samples/profile

build_Samples_profile: postbuild_Samples_profile
postbuild_Samples_profile: mainbuild_Samples_profile
mainbuild_Samples_profile: prebuild_Samples_profile $(Samples_profile_bin)
prebuild_Samples_profile:

$(Samples_profile_bin): $(Samples_profile_obj) build_MojoShader_profile build_PxToolkit_profile build_SampleBase_profile 
	mkdir -p `dirname ./../../lib/android16/libSamplesPROFILE.so`
	$(CXX) -shared $(Samples_profile_obj) $(Samples_profile_lflags) -lc -o $@ 
	$(ECHO) building $@ complete!

Samples_profile_DEPDIR = $(dir $(@))/$(*F)
$(Samples_profile_cpp_o): $(Samples_profile_objsdir)/%.o:
	$(ECHO) Samples: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cppfiles))))))
	cp $(Samples_profile_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  rm -f $(Samples_profile_DEPDIR).d

$(Samples_profile_cc_o): $(Samples_profile_objsdir)/%.o:
	$(ECHO) Samples: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_ccfiles))))))
	cp $(Samples_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_ccfiles))))).profile.P; \
	  rm -f $(Samples_profile_DEPDIR).d

$(Samples_profile_c_o): $(Samples_profile_objsdir)/%.o:
	$(ECHO) Samples: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(Samples_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cfiles))))))
	cp $(Samples_profile_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_profile_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  rm -f $(Samples_profile_DEPDIR).d

Samples_release_hpaths    := 
Samples_release_hpaths    += ./../../SampleBase
Samples_release_hpaths    += ./../../PxToolkit/include
Samples_release_hpaths    += ./../../SampleFramework/framework/include
Samples_release_hpaths    += ./../../SampleFramework/renderer/include
Samples_release_hpaths    += ./../../SampleFramework/platform/include
Samples_release_hpaths    += ./../../../Include
Samples_release_hpaths    += ./../../../Source/foundation/include
Samples_release_hpaths    += ./../../../Source/Common/src
Samples_release_hpaths    += ./../../../Source/GeomUtils/headers
Samples_release_hpaths    += ./../../../Source/GeomUtils/include
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/contact
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/common
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/convex
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/distance
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/gjk
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/intersection
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/mesh
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/Ice
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/hf
Samples_release_hpaths    += ./../../../Source/GeomUtils/src/pcm
Samples_release_hpaths    += ./../../../Include/foundation
Samples_release_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
Samples_release_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
Samples_release_hpaths    += ./../../../Include/common
Samples_release_hpaths    += ./../../SampleCCTSharedCode
Samples_release_hpaths    += ./../../../Source/PhysXVehicle/src
Samples_release_lpaths    := 
Samples_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
Samples_release_lpaths    += ./../../../Lib/android16
Samples_release_lpaths    += ./../../lib/android16
Samples_release_lpaths    += ./../../SampleFramework/platform/lib/android16
Samples_release_lpaths    += ./../../SampleFramework/renderer/lib/android16
Samples_release_lpaths    += ./../../SampleFramework/framework/lib/android16
Samples_release_lpaths    += ./../../PxToolkit/lib/android16
Samples_release_lpaths    += ./../../../externals/mojoshader/1067/lib/android16
Samples_release_lpaths    += ./../../PxToolkit/lib/android16
Samples_release_lpaths    += ./../../lib/android16
Samples_release_defines   := $(Samples_custom_defines)
Samples_release_defines   += ANDROID
Samples_release_defines   += GLES2
Samples_release_defines   += __ARM_ARCH_5__
Samples_release_defines   += __ARM_ARCH_5T__
Samples_release_defines   += __ARM_ARCH_5E__
Samples_release_defines   += __ARM_ARCH_5TE__
Samples_release_defines   += NDEBUG
Samples_release_defines   += PHYSX_PROFILE_SDK
Samples_release_libraries := 
Samples_release_libraries += MojoShader
Samples_release_libraries += PxToolkit
Samples_release_libraries += SampleBase
Samples_release_libraries += log
Samples_release_libraries += android
Samples_release_libraries += EGL
Samples_release_libraries += GLESv2
Samples_release_libraries += supc++
Samples_release_libraries += gnustl_static
Samples_release_libraries += nvToolsExt
Samples_release_libraries += PxToolkit
Samples_release_libraries += SampleBase
Samples_release_libraries += SampleFramework-MT
Samples_release_libraries += SampleRenderer-MT
Samples_release_libraries += SamplePlatform-MT
Samples_release_libraries += PhysX3Common
Samples_release_libraries += PhysX3
Samples_release_libraries += PhysX3Vehicle
Samples_release_libraries += PhysX3Cooking
Samples_release_libraries += PhysX3Extensions
Samples_release_libraries += PhysX3CharacterKinematic
Samples_release_common_cflags	:= $(Samples_custom_cflags)
Samples_release_common_cflags    += -MMD
Samples_release_common_cflags    += $(addprefix -D, $(Samples_release_defines))
Samples_release_common_cflags    += $(addprefix -I, $(Samples_release_hpaths))
Samples_release_common_cflags  += -Werror
Samples_release_common_cflags  += -fpic -fno-exceptions
Samples_release_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_release_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
Samples_release_common_cflags  += -O3 -fno-strict-aliasing
Samples_release_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
Samples_release_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
Samples_release_cflags	:= $(Samples_release_common_cflags)
Samples_release_cppflags	:= $(Samples_release_common_cflags)
Samples_release_cppflags  += -fno-rtti
Samples_release_lflags    := $(Samples_custom_lflags)
Samples_release_lflags    += $(addprefix -L, $(Samples_release_lpaths))
Samples_release_lflags    += -Wl,--start-group $(addprefix -l, $(Samples_release_libraries)) -Wl,--end-group
Samples_release_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
Samples_release_lflags  += -Wl,--no-undefined
Samples_release_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
Samples_release_objsdir  = $(OBJS_DIR)/Samples_release
Samples_release_cpp_o    = $(addprefix $(Samples_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(Samples_cppfiles)))))
Samples_release_cc_o    = $(addprefix $(Samples_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(Samples_ccfiles)))))
Samples_release_c_o      = $(addprefix $(Samples_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(Samples_cfiles)))))
Samples_release_obj      = $(Samples_release_cpp_o) $(Samples_release_cc_o) $(Samples_release_c_o)
Samples_release_bin      := ./../../lib/android16/libSamples.so

clean_Samples_release: 
	@$(ECHO) clean Samples release
	@$(RMDIR) $(Samples_release_objsdir)
	@$(RMDIR) $(Samples_release_bin)
	@$(RMDIR) $(DEPSDIR)/Samples/release

build_Samples_release: postbuild_Samples_release
postbuild_Samples_release: mainbuild_Samples_release
mainbuild_Samples_release: prebuild_Samples_release $(Samples_release_bin)
prebuild_Samples_release:

$(Samples_release_bin): $(Samples_release_obj) build_MojoShader_release build_PxToolkit_release build_SampleBase_release 
	mkdir -p `dirname ./../../lib/android16/libSamples.so`
	$(CXX) -shared $(Samples_release_obj) $(Samples_release_lflags) -lc -o $@ 
	$(ECHO) building $@ complete!

Samples_release_DEPDIR = $(dir $(@))/$(*F)
$(Samples_release_cpp_o): $(Samples_release_objsdir)/%.o:
	$(ECHO) Samples: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cppfiles))))))
	cp $(Samples_release_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cppfiles))))).P; \
	  rm -f $(Samples_release_DEPDIR).d

$(Samples_release_cc_o): $(Samples_release_objsdir)/%.o:
	$(ECHO) Samples: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_release_objsdir),, $@))), $(Samples_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(Samples_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_release_objsdir),, $@))), $(Samples_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_release_objsdir),, $@))), $(Samples_ccfiles))))))
	cp $(Samples_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_release_objsdir),, $@))), $(Samples_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(Samples_release_objsdir),, $@))), $(Samples_ccfiles))))).release.P; \
	  rm -f $(Samples_release_DEPDIR).d

$(Samples_release_c_o): $(Samples_release_objsdir)/%.o:
	$(ECHO) Samples: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(Samples_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cfiles))))))
	cp $(Samples_release_DEPDIR).d $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(Samples_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/Samples/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(Samples_release_objsdir),, $@))), $(Samples_cfiles))))).P; \
	  rm -f $(Samples_release_DEPDIR).d

clean_Samples:  clean_Samples_debug clean_Samples_checked clean_Samples_profile clean_Samples_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
