ps_3_0
// cgc version 2.2.0017, build date Jan 29 2010
// command line args: -profile ps_3_0 -I../include -DGLSL_COMPILER -DPASS_DEPTH -DNO_SUPPORT_DDX_DDY
// source file: tablet_buttons.cg
//vendor NVIDIA Corporation
//version 2.2.0.17
//profile ps_3_0
//program fmain
//semantic diffuseColor
//var float4 diffuseColor :  : c[0] : -1 : 1
//var float4 fmain.color : $vout.COLOR0 : COL : -1 : 1
mov oC0, c0
