PxShapeExt Class Reference
Main Page Class Hierarchy Compound List Compound Members
PxShapeExt Class Reference
Extensions
utility functions for use with PxShape
#include <PxShapeExt.h>
Static Public Member Functions
static PX_INLINE PxTransform getGlobalPose (const PxShape &shape, const PxRigidActor &actor)
Retrieves the world space pose of the shape.
static PX_INLINE PxU32 raycast (const PxShape &shape, const PxRigidActor &actor, const PxVec3 &rayOrigin, const PxVec3 &rayDir, PxReal maxDist, PxHitFlags hitFlags, PxU32 maxHits, PxRaycastHit *rayHits, bool anyHit)
Raycast test against the shape.
static PX_INLINE bool overlap (const PxShape &shape, const PxRigidActor &actor, const PxGeometry &otherGeom, const PxTransform &otherGeomPose)
Test overlap between the shape and a geometry object.
static PX_INLINE bool sweep (const PxShape &shape, const PxRigidActor &actor, const PxVec3 &unitDir, const PxReal distance, const PxGeometry &otherGeom, const PxTransform &otherGeomPose, PxSweepHit &sweepHit, PxHitFlags hitFlags)
Sweep a geometry object against the shape.
static PX_INLINE PxBounds3 getWorldBounds (const PxShape &shape, const PxRigidActor &actor, float inflation=1.01f)
Retrieves the axis aligned bounding box enclosing the shape.
Detailed Description
utility functions for use with PxShape
See Also
PxShape
Member Function Documentation
static PX_INLINE PxTransform PxShapeExt::getGlobalPose (const PxShape & shape, const PxRigidActor & actor) inline static
Retrieves the world space pose of the shape.
Parameters
[in] shape The shape for which to get the global pose.
[in] actor The actor to which the shape is attached
Returns
Global pose of shape.
References PxRigidActor::getGlobalPose(), and PxShape::getLocalPose().
static PX_INLINE PxBounds3 PxShapeExt::getWorldBounds (const PxShape & shape, const PxRigidActor & actor, float inflation = 1.01f) inline static
Retrieves the axis aligned bounding box enclosing the shape.
Returns
The shape's bounding box.
Parameters
[in] shape the shape
[in] actor the actor to which the shape is attached
[in] inflation Scale factor for computed world bounds. Box extents are multiplied by this value.
See Also
PxBounds3
References PxGeometryHolder::any(), PxShape::getGeometry(), and PxGeometryQuery::getWorldBounds().
static PX_INLINE bool PxShapeExt::overlap (const PxShape & shape, const PxRigidActor & actor, const PxGeometry & otherGeom, const PxTransform & otherGeomPose) inline static
Test overlap between the shape and a geometry object.
Parameters
[in] shape the shape
[in] actor the actor to which the shape is attached
[in] otherGeom The other geometry object to test overlap with
[in] otherGeomPose Pose of the other geometry object
Returns
True if the shape overlaps the geometry object
See Also
PxGeometry PxTransform
References PxGeometryHolder::any(), PxShape::getGeometry(), and PxGeometryQuery::overlap().
static PX_INLINE PxU32 PxShapeExt::raycast (const PxShape & shape, const PxRigidActor & actor, const PxVec3 & rayOrigin, const PxVec3 & rayDir, PxReal maxDist, PxHitFlags hitFlags, PxU32 maxHits, PxRaycastHit * rayHits, bool anyHit) inline static
Raycast test against the shape.
Parameters
[in] shape the shape
[in] actor the actor to which the shape is attached
[in] rayOrigin The origin of the ray to test the geometry object against
[in] rayDir The direction of the ray to test the geometry object against
[in] maxDist Maximum ray length
[in] hitFlags Specify which properties per hit should be computed and written to result hit array. Combination of PxHitFlag flags
[in] maxHits max number of returned hits = size of 'rayHits' buffer
[out] rayHits Raycast hits information
[in] anyHit Set to false if the closest hit point should be computed, else the query aborts as soon as any valid hit point is found.
Returns
Number of hits between the ray and the shape
See Also
PxRaycastHit PxTransform
References PxGeometryHolder::any(), PxShape::getGeometry(), and PxGeometryQuery::raycast().
static PX_INLINE bool PxShapeExt::sweep (const PxShape & shape, const PxRigidActor & actor, const PxVec3 & unitDir, const PxReal distance, const PxGeometry & otherGeom, const PxTransform & otherGeomPose, PxSweepHit & sweepHit, PxHitFlags hitFlags) inline static
Sweep a geometry object against the shape.
Currently only box, sphere, capsule and convex mesh shapes are supported, i.e. the swept geometry object must be one of those types.
Parameters
[in] shape the shape
[in] actor the actor to which the shape is attached
[in] unitDir Normalized direction along which the geometry object should be swept.
[in] distance Sweep distance. Needs to be larger than 0.
[in] otherGeom The geometry object to sweep against the shape
[in] otherGeomPose Pose of the geometry object
[out] sweepHit The sweep hit information. Only valid if this method returns true.
[in] hitFlags Specify which properties per hit should be computed and written to result hit array. Combination of PxHitFlag flags
Returns
True if the swept geometry object hits the shape
See Also
PxGeometry PxTransform PxSweepHit
References PxGeometryHolder::any(), PxShape::getGeometry(), and PxGeometryQuery::sweep().
The documentation for this class was generated from the following file:
PxShapeExt.h
Copyright © 2008-2015 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com