PxJointLinearLimitPair Class Reference
Main Page Class Hierarchy Compound List Compound Members
PxJointLinearLimitPair Class Reference
Extensions
Describes a two-sided limit.
#include <PxJointLimit.h>
Public Member Functions
PxJointLinearLimitPair (const PxTolerancesScale &scale, PxReal lowerLimit, PxReal upperLimit, PxReal contactDist=-1)
Construct a linear hard limit pair. The lower distance value must be less than the upper distance value.
PxJointLinearLimitPair (PxReal lowerLimit, PxReal upperLimit, const PxSpring &spring)
construct a linear soft limit pair
PX_INLINE bool isValid () const
Returns true if the limit is valid.
Public Member Functions inherited from PxJointLimitParameters
PxJointLimitParameters ()
PX_INLINE bool isValid () const
Returns true if the current settings are valid.
PX_INLINE bool isSoft () const
Public Attributes
PxReal upper
the range of the limit. The upper limit must be no lower than the lower limit, and if they are equal the limited degree of freedom will be treated as locked.
PxReal lower
Public Attributes inherited from PxJointLimitParameters
PxReal restitution
Controls the amount of bounce when the joint hits a limit.
PxReal bounceThreshold
PxReal stiffness
if greater than zero, the limit is soft, i.e. a spring pulls the joint back to the limit
PxReal damping
if spring is greater than zero, this is the damping of the limit spring
PxReal contactDistance
the distance inside the limit value at which the limit will be considered to be active by the solver. As this value is made larger, the limit becomes active more quickly. It thus becomes less likely to violate the extents of the limit, but more expensive.
Additional Inherited Members
Protected Member Functions inherited from PxJointLimitParameters
~PxJointLimitParameters ()
Detailed Description
Describes a two-sided limit.
Constructor & Destructor Documentation
PxJointLinearLimitPair::PxJointLinearLimitPair (const PxTolerancesScale & scale, PxReal lowerLimit, PxReal upperLimit, PxReal contactDist = -1) inline
Construct a linear hard limit pair. The lower distance value must be less than the upper distance value.
Parameters
[in] scale a PxTolerancesScale struct. Should be the same as used when creating the PxPhysics object.
[in] lowerLimit the lower distance of the limit
[in] upperLimit the upper distance of the limit
[in] contactDist the distance from the limit at which it becomes active. Default is the lesser of 0.01f scaled by the tolerance length scale, and 0.49 * (upperLimit - lowerLimit)
See Also
PxJointLimitParameters PxTolerancesScale
References PxJointLimitParameters::contactDistance, PxTolerancesScale::length, and PxMin().
PxJointLinearLimitPair::PxJointLinearLimitPair (PxReal lowerLimit, PxReal upperLimit, const PxSpring & spring) inline
construct a linear soft limit pair
Parameters
[in] lowerLimit the lower distance of the limit
[in] upperLimit the upper distance of the limit
[in] spring the stiffness and damping parameters of the limit spring
See Also
PxJointLimitParameters PxTolerancesScale
References damping, PxSpring::damping, stiffness, and PxSpring::stiffness.
Member Function Documentation
PX_INLINE bool PxJointLinearLimitPair::isValid () const inline
Returns true if the limit is valid.
Returns
true if the current settings are valid
References PxJointLimitParameters::isValid(), and PxIsFinite().
Member Data Documentation
PxReal PxJointLinearLimitPair::lower
PxReal PxJointLinearLimitPair::upper
the range of the limit. The upper limit must be no lower than the lower limit, and if they are equal the limited degree of freedom will be treated as locked.
Unit: Angular: Radians Range: See the joint on which the limit is used for details
Default: 0.0
The documentation for this class was generated from the following file:
PxJointLimit.h
Copyright © 2008-2015 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com