PxRigidActor Class Reference
Main Page Class Hierarchy Compound List Compound Members
PxRigidActor Class Reference abstract
Physics
PxRigidActor represents a base class shared between dynamic and static rigid bodies in the physics SDK.
#include <PxRigidActor.h>
Public Member Functions
virtual void release ()=0
Deletes the rigid actor object.
Global Pose Manipulation
virtual PxTransform getGlobalPose () const =0
Retrieves the actors world space transform.
virtual void setGlobalPose (const PxTransform &pose, bool autowake=true)=0
Method for setting an actor's pose in the world.
Shapes
virtual PxShape * createShape (const PxGeometry &geometry, PxMaterial *const *materials, PxU16 materialCount, PxShapeFlags shapeFlags=PxShapeFlag::eVISUALIZATION|PxShapeFlag::eSCENE_QUERY_SHAPE|PxShapeFlag::eSIMULATION_SHAPE)=0
Creates a new shape with default properties and a list of materials and adds it to the list of shapes of this actor.
PX_DEPRECATED PX_INLINE PxShape * createShape (const PxGeometry &geometry, PxMaterial *const *materials, PxU32 materialCount, const PxTransform &localPose)
Deprecated function to create shapes with an initial transform.
PX_FORCE_INLINE PxShape * createShape (const PxGeometry &geometry, const PxMaterial &material, PxShapeFlags shapeFlags=PxShapeFlag::eVISUALIZATION|PxShapeFlag::eSCENE_QUERY_SHAPE|PxShapeFlag::eSIMULATION_SHAPE)
Creates a new shape with default properties and a single material adds it to the list of shapes of this actor.
PX_DEPRECATED PX_INLINE PxShape * createShape (const PxGeometry &geometry, const PxMaterial &material, const PxTransform &localPose)
Deprecated function to create shapes with an initial transform.
virtual void attachShape (PxShape &shape)=0
virtual void detachShape (PxShape &shape, bool wakeOnLostTouch=true)=0
virtual PxU32 getNbShapes () const =0
Returns the number of shapes assigned to the actor.
virtual PxU32 getShapes (PxShape **userBuffer, PxU32 bufferSize, PxU32 startIndex=0) const =0
Retrieve all the shape pointers belonging to the actor.
Public Member Functions inherited from PxActor
virtual PxActorType::Enum getType () const =0
Retrieves the type of actor.
PX_DEPRECATED PX_INLINE
PxRigidStatic * isRigidStatic ()
Attempts to cast to specific actor type.
PX_DEPRECATED PX_INLINE const
PxRigidStatic * isRigidStatic () const
PX_DEPRECATED PX_INLINE
PxRigidDynamic * isRigidDynamic ()
PX_DEPRECATED PX_INLINE const
PxRigidDynamic * isRigidDynamic () const
PX_DEPRECATED PX_INLINE
PxParticleSystem * isParticleSystem ()
PX_DEPRECATED PX_INLINE const
PxParticleSystem * isParticleSystem () const
PX_DEPRECATED PX_INLINE
PxParticleFluid * isParticleFluid ()
PX_DEPRECATED PX_INLINE const
PxParticleFluid * isParticleFluid () const
PX_DEPRECATED PX_INLINE
PxArticulationLink * isArticulationLink ()
PX_DEPRECATED PX_INLINE const
PxArticulationLink * isArticulationLink () const
PX_DEPRECATED PX_INLINE PxCloth * isCloth ()
PX_DEPRECATED PX_INLINE const
PxCloth * isCloth () const
PX_DEPRECATED PX_INLINE
PxRigidActor * isRigidActor ()
PX_DEPRECATED PX_INLINE const
PxRigidActor * isRigidActor () const
PX_DEPRECATED PX_INLINE
PxRigidBody * isRigidBody ()
PX_DEPRECATED PX_INLINE const
PxRigidBody * isRigidBody () const
PX_DEPRECATED PX_INLINE
PxParticleBase * isParticleBase ()
PX_DEPRECATED PX_INLINE const
PxParticleBase * isParticleBase () const
virtual PxScene * getScene () const =0
Retrieves the scene which this actor belongs to.
virtual void setName (const char *name)=0
Sets a name string for the object that can be retrieved with getName().
virtual const char * getName () const =0
Retrieves the name string set with setName().
virtual PxBounds3 getWorldBounds (float inflation=1.01f) const =0
Retrieves the axis aligned bounding box enclosing the actor.
virtual void setActorFlag (PxActorFlag::Enum flag, bool value)=0
Raises or clears a particular actor flag.
virtual void setActorFlags (PxActorFlags inFlags)=0
sets the actor flags
virtual PxActorFlags getActorFlags () const =0
Reads the PxActor flags.
virtual void setDominanceGroup (PxDominanceGroup dominanceGroup)=0
Assigns dynamic actors a dominance group identifier.
virtual PxDominanceGroup getDominanceGroup () const =0
Retrieves the value set with setDominanceGroup().
virtual void setOwnerClient (PxClientID inClient)=0
Sets the owner client of an actor.
virtual PxClientID getOwnerClient () const =0
Returns the owner client that was specified with at creation time.
virtual void setClientBehaviorFlags (PxActorClientBehaviorFlags)=0
Sets the behavior bits of the actor.
virtual PxActorClientBehaviorFlags getClientBehaviorFlags () const =0
Retrieves the behavior bits of the actor.
virtual PxAggregate * getAggregate () const =0
Retrieves the aggregate the actor might be a part of.
Public Member Functions inherited from PxBase
virtual const char * getConcreteTypeName () const
Returns string name of dynamic type.
template<class T >
T * is ()
template<class T >
const T * is () const
PX_INLINE PxType getConcreteType () const
Returns concrete type of object.
PX_INLINE void setBaseFlag (PxBaseFlag::Enum flag, bool value)
Set PxBaseFlag.
PX_INLINE void setBaseFlags (PxBaseFlags inFlags)
Set PxBaseFlags.
PX_INLINE PxBaseFlags getBaseFlags () const
Returns PxBaseFlags.
virtual bool isReleasable () const
Whether the object is subordinate.
Constraints
virtual PxU32 getNbConstraints () const =0
Returns the number of constraint shaders attached to the actor.
virtual PxU32 getConstraints (PxConstraint **userBuffer, PxU32 bufferSize, PxU32 startIndex=0) const =0
Retrieve all the constraint shader pointers belonging to the actor.
PX_INLINE PxRigidActor (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxRigidActor (PxBaseFlags baseFlags)
virtual ~PxRigidActor ()
virtual bool isKindOf (const char *name) const
Returns whether a given type name matches with the type of this instance.
Additional Inherited Members
Public Attributes inherited from PxActor
void * userData
user can assign this to whatever, usually to create a 1:1 relationship with a user object.
Protected Member Functions inherited from PxActor
PX_INLINE PxActor (PxType concreteType, PxBaseFlags baseFlags)
PX_INLINE PxActor (PxBaseFlags baseFlags)
virtual ~PxActor ()
Protected Attributes inherited from PxBase
PxType mConcreteType
PxBaseFlags mBaseFlags
Detailed Description
PxRigidActor represents a base class shared between dynamic and static rigid bodies in the physics SDK.
PxRigidActor objects specify the geometry of the object by defining a set of attached shapes (see PxShape, createShape()).
See Also
PxActor
Constructor & Destructor Documentation
PX_INLINE PxRigidActor::PxRigidActor (PxType concreteType, PxBaseFlags baseFlags) inline protected
PX_INLINE PxRigidActor::PxRigidActor (PxBaseFlags baseFlags) inline protected
virtual PxRigidActor::~PxRigidActor () inline protected virtual
Member Function Documentation
virtual void PxRigidActor::attachShape (PxShape & shape) pure virtual
attach a shared shape to an actor
This call will increment the reference count of the shape.
Note
Mass properties of dynamic rigid actors will not automatically be recomputed to reflect the new mass distribution implied by the shape. Follow this call with a call to the PhysX extensions method PxRigidBodyExt::updateMassAndInertia() to do that.
Attaching a triangle mesh, heightfield or plane geometry shape configured as eSIMULATION_SHAPE is not supported for non-kinematic PxRigidDynamic instances.
Sleeping: Does NOT wake the actor up automatically.
Parameters
[in] shape the shape to attach.
virtual PxShape* PxRigidActor::createShape (const PxGeometry & geometry, PxMaterial *const * materials, PxU16 materialCount, PxShapeFlags shapeFlags = PxShapeFlag::eVISUALIZATION|PxShapeFlag::eSCENE_QUERY_SHAPE|PxShapeFlag::eSIMULATION_SHAPE) pure virtual
Creates a new shape with default properties and a list of materials and adds it to the list of shapes of this actor.
This is equivalent to the following
PxShape* shape(...) = PxGetPhysics().createShape(...); // reference count is 1 actor->attachShape(shape); // increments reference count shape->release(); // releases user reference, leaving reference count at 1
As a consequence, detachShape() will result in the release of the last reference, and the shape will be deleted.
Note
The default shape flags to be set are: eVISUALIZATION, eSIMULATION_SHAPE, eSCENE_QUERY_SHAPE (see PxShapeFlag). Triangle mesh, heightfield or plane geometry shapes configured as eSIMULATION_SHAPE are not supported for non-kinematic PxRigidDynamic instances.
Creating compounds with a very large number of shapes may adversely affect performance and stability.
Sleeping: Does NOT wake the actor up automatically.
Parameters
[in] geometry the geometry of the shape
[in] materials a pointer to an array of material pointers
[in] materialCount the count of materials
[in] shapeFlags optional PxShapeFlags
Returns
The newly created shape.
See Also
PxShape PxShape::release()
PX_DEPRECATED PX_INLINE PxShape* PxRigidActor::createShape (const PxGeometry & geometry, PxMaterial *const * materials, PxU32 materialCount, const PxTransform & localPose) inline
Deprecated function to create shapes with an initial transform.
Deprecated:
Use this instead: PxShape* shape = actor->createShape(geometry, materials, materialCount); if (shape) shape->setLocalPose(transform);
See Also
PxShape, createShape(const PxGeometry& geometry, PxMaterial*const* materials, PxU16 materialCount, PxShapeFlags shapeFlags = PxShapeFlag::eVISUALIZATION | PxShapeFlag::eSCENE_QUERY_SHAPE | PxShapeFlag::eSIMULATION_SHAPE)
References PxShape::setLocalPose().
PX_FORCE_INLINE PxShape* PxRigidActor::createShape (const PxGeometry & geometry, const PxMaterial & material, PxShapeFlags shapeFlags = PxShapeFlag::eVISUALIZATION | PxShapeFlag::eSCENE_QUERY_SHAPE | PxShapeFlag::eSIMULATION_SHAPE) inline
Creates a new shape with default properties and a single material adds it to the list of shapes of this actor.
This is equivalent to the following
PxShape* shape(...) = PxGetPhysics().createShape(...); // reference count is 1 actor->attachShape(shape); // increments reference count shape->release(); // releases user reference, leaving reference count at 1
As a consequence, detachShape() will result in the release of the last reference, and the shape will be deleted.
Note
The default shape flags to be set are: eVISUALIZATION, eSIMULATION_SHAPE, eSCENE_QUERY_SHAPE (see PxShapeFlag). Triangle mesh, heightfield or plane geometry shapes configured as eSIMULATION_SHAPE are not supported for non-kinematic PxRigidDynamic instances.
Creating compounds with a very large number of shapes may adversely affect performance and stability.
Sleeping: Does NOT wake the actor up automatically.
Parameters
[in] geometry the geometry of the shape
[in] material the material for the shape
[in] shapeFlags optional PxShapeFlags
Returns
The newly created shape.
See Also
PxShape PxShape::release() detachShape()
PX_DEPRECATED PX_INLINE PxShape* PxRigidActor::createShape (const PxGeometry & geometry, const PxMaterial & material, const PxTransform & localPose) inline
Deprecated function to create shapes with an initial transform.
Deprecated:
Use this instead: PxShape* shape = actor->createShape(geometry, material); if (shape) shape->setLocalPose(transform);
See Also
PxShape, createShape(const PxGeometry& geometry, const PxMaterial& material, PxShapeFlags shapeFlags = PxShapeFlag::eVISUALIZATION | PxShapeFlag::eSCENE_QUERY_SHAPE | PxShapeFlag::eSIMULATION_SHAPE)
References PxShape::setLocalPose().
virtual void PxRigidActor::detachShape (PxShape & shape, bool wakeOnLostTouch = true) pure virtual
detach a shape from an actor.
This will also decrement the reference count of the PxShape, and if the reference count is zero, will cause it to be deleted.
For static rigid actors it is not possible to detach all shapes associated with the actor. An attempt to remove the last shape will be ignored.
Sleeping: Does NOT wake the actor up automatically.
Parameters
[in] shape the shape to detach.
[in] wakeOnLostTouch Specifies whether touching objects from the previous frame should get woken up in the next frame. Only applies to PxArticulation and PxRigidActor types.
virtual PxU32 PxRigidActor::getConstraints (PxConstraint ** userBuffer, PxU32 bufferSize, PxU32 startIndex = 0) const pure virtual
Retrieve all the constraint shader pointers belonging to the actor.
You can retrieve the number of constraint shader pointers by calling getNbConstraints()
Note: Removing constraint shaders with PxConstraint::release() will invalidate the pointer of the released constraint.
Parameters
[out] userBuffer The buffer to store the constraint shader pointers.
[in] bufferSize Size of provided user buffer.
[in] startIndex Index of first constraint pointer to be retrieved
Returns
Number of constraint shader pointers written to the buffer.
See Also
PxConstraint getNbConstraints() PxConstraint::release()
virtual PxTransform PxRigidActor::getGlobalPose () const pure virtual
Retrieves the actors world space transform.
The getGlobalPose() method retrieves the actor's current actor space to world space transformation.
Returns
Global pose of object.
See Also
PxRigidDynamic.setGlobalPose() PxRigidStatic.setGlobalPose()
Referenced by PxShapeExt::getGlobalPose().
virtual PxU32 PxRigidActor::getNbConstraints () const pure virtual
Returns the number of constraint shaders attached to the actor.
You can use getConstraints() to retrieve the constraint shader pointers.
Returns
Number of constraint shaders attached to this actor.
See Also
PxConstraint getConstraints()
virtual PxU32 PxRigidActor::getNbShapes () const pure virtual
Returns the number of shapes assigned to the actor.
You can use getShapes() to retrieve the shape pointers.
Returns
Number of shapes associated with this actor.
See Also
PxShape getShapes()
virtual PxU32 PxRigidActor::getShapes (PxShape ** userBuffer, PxU32 bufferSize, PxU32 startIndex = 0) const pure virtual
Retrieve all the shape pointers belonging to the actor.
These are the shapes used by the actor for collision detection.
You can retrieve the number of shape pointers by calling getNbShapes()
Note: Removing shapes with PxShape::release() will invalidate the pointer of the released shape.
Parameters
[out] userBuffer The buffer to store the shape pointers.
[in] bufferSize Size of provided user buffer.
[in] startIndex Index of first shape pointer to be retrieved
Returns
Number of shape pointers written to the buffer.
See Also
PxShape getNbShapes() PxShape::release()
virtual bool PxRigidActor::isKindOf (const char * superClass) const inline protected virtual
Returns whether a given type name matches with the type of this instance.
Reimplemented from PxActor.
Reimplemented in PxRigidBody, PxRigidDynamic, PxArticulationLink, and PxRigidStatic.
References PxActor::isKindOf().
Referenced by PxRigidStatic::isKindOf(), and PxRigidBody::isKindOf().
virtual void PxRigidActor::release () pure virtual
Deletes the rigid actor object.
Also releases any shapes associated with the actor.
Releasing an actor will affect any objects that are connected to the actor (constraint shaders like joints etc.). Such connected objects will be deleted upon scene deletion, or explicitly by the user by calling release() on these objects. It is recommended to always remove all objects that reference actors before the actors themselves are removed. It is not possible to retrieve list of dead connected objects.
Sleeping: This call will awaken any sleeping actors contacting the deleted actor (directly or indirectly).
Calls PxActor::release() so you might want to check the documentation of that method as well.
See Also
PxActor::release()
Implements PxActor.
Implemented in PxArticulationLink.
virtual void PxRigidActor::setGlobalPose (const PxTransform & pose, bool autowake = true) pure virtual
Method for setting an actor's pose in the world.
This method instantaneously changes the actor space to world space transformation.
This method is mainly for dynamic rigid bodies (see PxRigidDynamic). Calling this method on static actors is likely to result in a performance penalty, since internal optimization structures for static actors may need to be recomputed. In addition, moving static actors will not interact correctly with dynamic actors or joints.
To directly control an actor's position and have it correctly interact with dynamic bodies and joints, create a dynamic body with the PxRigidBodyFlag::eKINEMATIC flag, then use the setKinematicTarget() commands to define its path.
Even when moving dynamic actors, exercise restraint in making use of this method. Where possible, avoid:
moving actors into other actors, thus causing overlap (an invalid physical state)
moving an actor that is connected by a joint to another away from the other (thus causing joint error)
Sleeping: This call wakes dynamic actors if they are sleeping and the autowake parameter is true (default).
Parameters
[in] pose Transformation from the actors local frame to the global frame. Range: rigid body transform.
[in] autowake whether to wake the object if it is dynamic. This parameter has no effect for static or kinematic actors. If true and the current wake counter value is smaller than PxSceneDesc::wakeCounterResetValue it will get increased to the reset value.
See Also
getGlobalPose()
The documentation for this class was generated from the following file:
PxRigidActor.h
Copyright © 2008-2015 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com