PxJointLimitCone Class Reference
Main Page Class Hierarchy Compound List Compound Members
PxJointLimitCone Class Reference
Extensions
Describes an elliptical conical joint limit. Note that very small or highly elliptical limit cones may result in jitter.
#include <PxJointLimit.h>
Public Member Functions
PxJointLimitCone (PxReal yLimitAngle, PxReal zLimitAngle, PxReal contactDist=-1)
Construct a cone hard limit.
PxJointLimitCone (PxReal yLimitAngle, PxReal zLimitAngle, const PxSpring &spring)
Construct a cone soft limit.
PX_INLINE bool isValid () const
Returns true if the limit is valid.
Public Member Functions inherited from PxJointLimitParameters
PxJointLimitParameters ()
PX_INLINE bool isValid () const
Returns true if the current settings are valid.
PX_INLINE bool isSoft () const
Public Attributes
PxReal yAngle
the maximum angle from the Y axis of the constraint frame.
PxReal zAngle
the maximum angle from the Z-axis of the constraint frame.
Public Attributes inherited from PxJointLimitParameters
PxReal restitution
Controls the amount of bounce when the joint hits a limit.
PxReal bounceThreshold
PxReal stiffness
if greater than zero, the limit is soft, i.e. a spring pulls the joint back to the limit
PxReal damping
if spring is greater than zero, this is the damping of the limit spring
PxReal contactDistance
the distance inside the limit value at which the limit will be considered to be active by the solver. As this value is made larger, the limit becomes active more quickly. It thus becomes less likely to violate the extents of the limit, but more expensive.
Additional Inherited Members
Protected Member Functions inherited from PxJointLimitParameters
~PxJointLimitParameters ()
Detailed Description
Describes an elliptical conical joint limit. Note that very small or highly elliptical limit cones may result in jitter.
See Also
PxD6Joint PxSphericalJoint
Constructor & Destructor Documentation
PxJointLimitCone::PxJointLimitCone (PxReal yLimitAngle, PxReal zLimitAngle, PxReal contactDist = -1) inline
Construct a cone hard limit.
Parameters
[in] yLimitAngle the limit angle from the Y-axis of the constraint frame
[in] zLimitAngle the limit angle from the Z-axis of the constraint frame
[in] contactDist the distance from the limit at which it becomes active. Default is the lesser of 0.1 radians, and 0.49 * the lower of the limit angles
See Also
PxJointLimitParameters
References PxJointLimitParameters::contactDistance, and PxMin().
PxJointLimitCone::PxJointLimitCone (PxReal yLimitAngle, PxReal zLimitAngle, const PxSpring & spring) inline
Construct a cone soft limit.
Parameters
[in] yLimitAngle the limit angle from the Y-axis of the constraint frame
[in] zLimitAngle the limit angle from the Z-axis of the constraint frame
[in] spring the stiffness and damping of the limit spring
See Also
PxJointLimitParameters
References damping, PxSpring::damping, stiffness, and PxSpring::stiffness.
Member Function Documentation
PX_INLINE bool PxJointLimitCone::isValid () const inline
Returns true if the limit is valid.
Returns
true if the current settings are valid
References PxJointLimitParameters::isValid(), PxIsFinite(), and PxPi.
Member Data Documentation
PxReal PxJointLimitCone::yAngle
the maximum angle from the Y axis of the constraint frame.
Unit: Angular: Radians Range: Angular: (0,PI)
Default: PI/2
PxReal PxJointLimitCone::zAngle
the maximum angle from the Z-axis of the constraint frame.
Unit: Angular: Radians Range: Angular: (0,PI)
Default: PI/2
The documentation for this class was generated from the following file:
PxJointLimit.h
Copyright © 2008-2015 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com