Character
Main Page Class Hierarchy Compound List Compound Members
Character
Classes
class PxBoxControllerDesc
Descriptor for a box character controller.
class PxBoxController
Box character controller.
struct PxCapsuleClimbingMode
class PxCapsuleControllerDesc
A descriptor for a capsule character controller.
class PxCapsuleController
A capsule character controller.
struct PxControllerShapeType
The type of controller, eg box, sphere or capsule.
struct PxControllerNonWalkableMode
specifies how a CCT interacts with non-walkable parts.
struct PxControllerCollisionFlag
specifies which sides a character is colliding with.
struct PxControllerState
Describes a controller's internal state.
struct PxControllerStats
Describes a controller's internal statistics.
struct PxControllerHit
Describes a generic CCT hit.
struct PxControllerShapeHit
Describes a hit between a CCT and a shape. Passed to onShapeHit()
struct PxControllersHit
Describes a hit between a CCT and another CCT. Passed to onControllerHit().
struct PxControllerObstacleHit
Describes a hit between a CCT and a user-defined obstacle. Passed to onObstacleHit().
class PxUserControllerHitReport
User callback class for character controller events.
class PxControllerFilterCallback
Dedicated filtering callback for CCT vs CCT.
class PxControllerFilters
Filtering data for "move" call.
class PxControllerDesc
Descriptor class for a character controller.
class PxController
Base class for character controllers.
struct PxControllerBehaviorFlag
specifies controller behavior
class PxControllerBehaviorCallback
User behavior callback.
struct PxControllerDebugRenderFlag
specifies debug-rendering flags
class PxControllerManager
Manages an array of character controllers.
class PxObstacle
Base class for obstacles.
class PxBoxObstacle
A box obstacle.
class PxCapsuleObstacle
A capsule obstacle.
class PxObstacleContext
Context class for obstacles.
struct PxExtendedVec3
Macros
#define PX_PHYSX_CHARACTER_API
#define INVALID_OBSTACLE_HANDLE 0xffffffff
#define PX_BIG_WORLDS
#define PX_MAX_EXTENDED PX_MAX_F64
#define PxExtendedAbs(x) fabs(x)
Typedefs
typedef PX_DEPRECATED
PxControllerNonWalkableMode PxCCTNonWalkableMode
typedef PxFlags
< PxControllerCollisionFlag::Enum,
PxU8 > PxControllerCollisionFlags
Bitfield that contains a set of raised flags defined in PxControllerCollisionFlag.
typedef PX_DEPRECATED
PxControllerCollisionFlag PxControllerFlag
typedef PX_DEPRECATED
PxControllerCollisionFlags PxControllerFlags
typedef PX_DEPRECATED
PxControllerHit PxCCTHit
typedef PxFlags
< PxControllerBehaviorFlag::Enum,
PxU8 > PxControllerBehaviorFlags
Bitfield that contains a set of raised flags defined in PxControllerBehaviorFlag.
typedef PxFlags
< PxControllerDebugRenderFlag::Enum,
PxU32 > PxControllerDebugRenderFlags
Bitfield that contains a set of raised flags defined in PxControllerDebugRenderFlag.
typedef PxU32 ObstacleHandle
typedef double PxExtended
Functions
PX_C_EXPORT
PX_PHYSX_CHARACTER_API
physx::PxControllerManager
*PX_CALL_CONV PxCreateControllerManager (physx::PxScene &scene, bool lockingEnabled=false)
Creates the controller manager.
PX_FORCE_INLINE PxVec3 toVec3 (const PxExtendedVec3 &v)
PX_INLINE PxBoxControllerDesc::PxBoxControllerDesc ()
constructor sets to default.
PX_INLINE PxBoxControllerDesc::PxBoxControllerDesc (const PxBoxControllerDesc &)
copy constructor.
PX_INLINE PxBoxControllerDesc & PxBoxControllerDesc::operator= (const PxBoxControllerDesc &)
assignment operator.
PX_INLINE void PxBoxControllerDesc::copy (const PxBoxControllerDesc &)
virtual PX_INLINE void PxBoxControllerDesc::setToDefault ()
(re)sets the structure to the default.
virtual PX_INLINE bool PxBoxControllerDesc::isValid () const
returns true if the current settings are valid
PX_INLINE PxCapsuleControllerDesc::PxCapsuleControllerDesc ()
constructor sets to default.
PX_INLINE PxCapsuleControllerDesc::PxCapsuleControllerDesc (const PxCapsuleControllerDesc &)
copy constructor.
PX_INLINE PxCapsuleControllerDesc & PxCapsuleControllerDesc::operator= (const PxCapsuleControllerDesc &)
assignment operator.
PX_INLINE void PxCapsuleControllerDesc::copy (const PxCapsuleControllerDesc &)
virtual PX_INLINE void PxCapsuleControllerDesc::setToDefault ()
(re)sets the structure to the default.
virtual PX_INLINE bool PxCapsuleControllerDesc::isValid () const
returns true if the current settings are valid
PX_INLINE PxControllerDesc::PxControllerDesc (PxControllerShapeType::Enum)
constructor sets to default.
PX_INLINE PxControllerDesc::PxControllerDesc (const PxControllerDesc &)
copy constructor.
PX_INLINE PxControllerDesc & PxControllerDesc::operator= (const PxControllerDesc &)
assignment operator.
PX_INLINE void PxControllerDesc::copy (const PxControllerDesc &)
virtual PX_INLINE PxControllerDesc::~PxControllerDesc ()
virtual PX_INLINE bool PxControllerDesc::isValid () const
returns true if the current settings are valid
Detailed Description
Macro Definition Documentation
#define INVALID_OBSTACLE_HANDLE 0xffffffff
#define PX_BIG_WORLDS
#define PX_MAX_EXTENDED PX_MAX_F64
Referenced by PxExtendedVec3::setMinusInfinity(), and PxExtendedVec3::setPlusInfinity().
#define PX_PHYSX_CHARACTER_API
#define PxExtendedAbs (x) fabs(x)
Typedef Documentation
typedef PxU32 ObstacleHandle
typedef PX_DEPRECATED PxControllerHit PxCCTHit
Deprecated:
Deprecated definition for backwards compatibility with PhysX 3.2
typedef PX_DEPRECATED PxControllerNonWalkableMode PxCCTNonWalkableMode
Deprecated:
Deprecated definition for backwards compatibility with PhysX 3.2
typedef PxFlags<PxControllerBehaviorFlag::Enum, PxU8> PxControllerBehaviorFlags
Bitfield that contains a set of raised flags defined in PxControllerBehaviorFlag.
See Also
PxControllerBehaviorFlag
typedef PxFlags<PxControllerCollisionFlag::Enum, PxU8> PxControllerCollisionFlags
Bitfield that contains a set of raised flags defined in PxControllerCollisionFlag.
See Also
PxControllerCollisionFlag
typedef PxFlags<PxControllerDebugRenderFlag::Enum, PxU32> PxControllerDebugRenderFlags
Bitfield that contains a set of raised flags defined in PxControllerDebugRenderFlag.
See Also
PxControllerDebugRenderFlag
typedef PX_DEPRECATED PxControllerCollisionFlag PxControllerFlag
Deprecated:
Deprecated definition for backwards compatibility with PhysX 3.2
typedef PX_DEPRECATED PxControllerCollisionFlags PxControllerFlags
Deprecated:
Deprecated definition for backwards compatibility with PhysX 3.2
typedef double PxExtended
Function Documentation
PX_INLINE void PxBoxControllerDesc::copy (const PxBoxControllerDesc & other) protected
References PxBoxControllerDesc::halfForwardExtent, PxBoxControllerDesc::halfHeight, and PxBoxControllerDesc::halfSideExtent.
Referenced by PxBoxControllerDesc::operator=(), and PxBoxControllerDesc::PxBoxControllerDesc().
PX_INLINE void PxCapsuleControllerDesc::copy (const PxCapsuleControllerDesc & other) protected
References PxCapsuleControllerDesc::climbingMode, PxCapsuleControllerDesc::height, and PxCapsuleControllerDesc::radius.
Referenced by PxCapsuleControllerDesc::operator=(), and PxCapsuleControllerDesc::PxCapsuleControllerDesc().
PX_INLINE void PxControllerDesc::copy (const PxControllerDesc & other) protected
References PxControllerDesc::behaviorCallback, PxControllerDesc::callback, PxControllerDesc::contactOffset, PxControllerDesc::density, PxControllerDesc::invisibleWallHeight, PxControllerDesc::material, PxControllerDesc::maxJumpHeight, PxControllerDesc::nonWalkableMode, PxControllerDesc::position, PxControllerDesc::reportCallback, PxControllerDesc::scaleCoeff, PxControllerDesc::slopeLimit, PxControllerDesc::stepOffset, PxControllerDesc::upDirection, PxControllerDesc::userData, PxControllerDesc::volumeGrowth, PxExtendedVec3::x, PxExtendedVec3::y, and PxExtendedVec3::z.
Referenced by PxControllerDesc::operator=(), and PxControllerDesc::PxControllerDesc().
PX_INLINE bool PxBoxControllerDesc::isValid () const virtual
returns true if the current settings are valid
Returns
True if the descriptor is valid.
Reimplemented from PxControllerDesc.
References PxBoxControllerDesc::halfForwardExtent, PxBoxControllerDesc::halfHeight, PxBoxControllerDesc::halfSideExtent, PxControllerDesc::isValid(), and PxControllerDesc::stepOffset.
PX_INLINE bool PxCapsuleControllerDesc::isValid () const virtual
returns true if the current settings are valid
Returns
True if the descriptor is valid.
Reimplemented from PxControllerDesc.
References PxCapsuleControllerDesc::height, PxControllerDesc::isValid(), PxCapsuleControllerDesc::radius, and PxControllerDesc::stepOffset.
PX_INLINE bool PxControllerDesc::isValid () const virtual
returns true if the current settings are valid
Returns
True if the descriptor is valid.
Reimplemented in PxCapsuleControllerDesc, and PxBoxControllerDesc.
References PxControllerDesc::callback, PxControllerDesc::contactOffset, PxControllerDesc::density, PxControllerShapeType::eBOX, PxControllerShapeType::eCAPSULE, PxErrorCode::eDEBUG_WARNING, PxControllerDesc::material, PxControllerDesc::mType, PxGetFoundation(), PxControllerDesc::reportCallback, PxControllerDesc::scaleCoeff, PxControllerDesc::slopeLimit, PxControllerDesc::stepOffset, and PxControllerDesc::volumeGrowth.
Referenced by PxBoxControllerDesc::isValid(), and PxCapsuleControllerDesc::isValid().
PX_INLINE PxBoxControllerDesc & PxBoxControllerDesc::operator= (const PxBoxControllerDesc & other)
assignment operator.
References PxBoxControllerDesc::copy(), and PxControllerDesc::operator=().
PX_INLINE PxCapsuleControllerDesc & PxCapsuleControllerDesc::operator= (const PxCapsuleControllerDesc & other)
assignment operator.
References PxCapsuleControllerDesc::copy(), and PxControllerDesc::operator=().
PX_INLINE PxControllerDesc & PxControllerDesc::operator= (const PxControllerDesc & other) protected
assignment operator.
References PxControllerDesc::copy().
Referenced by PxBoxControllerDesc::operator=(), and PxCapsuleControllerDesc::operator=().
PX_INLINE PxBoxControllerDesc::PxBoxControllerDesc ()
constructor sets to default.
Referenced by PxBoxControllerDesc::setToDefault().
PX_INLINE PxBoxControllerDesc::PxBoxControllerDesc (const PxBoxControllerDesc & other)
copy constructor.
References PxBoxControllerDesc::copy().
PX_INLINE PxCapsuleControllerDesc::PxCapsuleControllerDesc ()
constructor sets to default.
References PxCapsuleControllerDesc::climbingMode, PxCapsuleClimbingMode::eEASY, PxCapsuleControllerDesc::height, and PxCapsuleControllerDesc::radius.
Referenced by PxCapsuleControllerDesc::setToDefault().
PX_INLINE PxCapsuleControllerDesc::PxCapsuleControllerDesc (const PxCapsuleControllerDesc & other)
copy constructor.
References PxCapsuleControllerDesc::copy().
PX_INLINE PxControllerDesc::PxControllerDesc (PxControllerShapeType::Enum t) protected
constructor sets to default.
References PxControllerDesc::behaviorCallback, PxControllerDesc::callback, PxControllerDesc::contactOffset, PxControllerDesc::density, PxControllerNonWalkableMode::ePREVENT_CLIMBING, PxControllerDesc::invisibleWallHeight, PxControllerDesc::material, PxControllerDesc::maxJumpHeight, PxControllerDesc::nonWalkableMode, NULL, PxControllerDesc::position, PxControllerDesc::reportCallback, PxControllerDesc::scaleCoeff, PxControllerDesc::slopeLimit, PxControllerDesc::stepOffset, PxControllerDesc::upDirection, PxControllerDesc::userData, PxControllerDesc::volumeGrowth, PxExtendedVec3::x, PxExtendedVec3::y, and PxExtendedVec3::z.
PX_INLINE PxControllerDesc::PxControllerDesc (const PxControllerDesc & other) protected
copy constructor.
References PxControllerDesc::copy().
PX_C_EXPORT PX_PHYSX_CHARACTER_API physx::PxControllerManager* PX_CALL_CONV PxCreateControllerManager (physx::PxScene & scene, bool lockingEnabled = false)
Creates the controller manager.
Parameters
[in] scene PhysX scene.
[in] lockingEnabled Enables/disables internal locking.
The character controller is informed by PxDeletionListener::onRelease() when actors or shapes are released, and updates its internal caches accordingly. If character controller movement or a call to PxControllerManager::shiftOrigin() may overlap with actor/shape releases, internal data structures must be guarded against concurrent access.
Locking guarantees thread safety in such scenarios.
Note
locking may result in significant slowdown for release of actors or shapes.
By default, locking is disabled.
PX_INLINE void PxBoxControllerDesc::setToDefault () virtual
(re)sets the structure to the default.
References PxBoxControllerDesc::PxBoxControllerDesc().
PX_INLINE void PxCapsuleControllerDesc::setToDefault () virtual
(re)sets the structure to the default.
References PxCapsuleControllerDesc::PxCapsuleControllerDesc().
PX_FORCE_INLINE PxVec3 toVec3 (const PxExtendedVec3 & v)
References PxExtendedVec3::x, PxExtendedVec3::y, and PxExtendedVec3::z.
PX_INLINE PxControllerDesc::~PxControllerDesc () protected virtual
Copyright © 2008-2015 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com