Serializers
Main Page Class Hierarchy Compound List Compound Members
Serializers
Classes
class PxRepXSerializer
Serializer interface for RepX (Xml) serialization.
Macros
#define PX_NEW_REPX_SERIALIZER(T) *PX_PLACEMENT_NEW(PxGetFoundation().getAllocatorCallback().allocate(sizeof(T), "PxRepXSerializer", __FILE__, __LINE__), T)(PxGetFoundation().getAllocatorCallback())
Preprocessor macro for RepX serializer creation.
#define PX_DELETE_REPX_SERIALIZER(x) { PxRepXSerializer* s = x; if (s) { PxGetFoundation().getAllocatorCallback().deallocate(s); } }
Preprocessor Macro to simplify RepX serializer delete.
Functions
template<typename TDataType >
PX_INLINE PxRepXObject createRepXObject (const TDataType *inType, const PxSerialObjectId inId)
Inline helper template function to create PxRepXObject from TDataType type supporting PxTypeInfo<TDataType>::name.
PX_INLINE PxRepXObject createRepXObject (const PxBase *inType, const PxSerialObjectId inId)
Inline helper function to create PxRepXObject from a PxBase instance.
template<typename TDataType >
PX_INLINE PxRepXObject createRepXObject (const TDataType *inType)
Inline helper template function to create PxRepXObject form TDataType type using inType pointer as a PxSerialObjectId id.
Detailed Description
Macro Definition Documentation
#define PX_DELETE_REPX_SERIALIZER (x) { PxRepXSerializer* s = x; if (s) { PxGetFoundation().getAllocatorCallback().deallocate(s); } }
Preprocessor Macro to simplify RepX serializer delete.
#define PX_NEW_REPX_SERIALIZER (T) *PX_PLACEMENT_NEW(PxGetFoundation().getAllocatorCallback().allocate(sizeof(T), "PxRepXSerializer", __FILE__, __LINE__), T)(PxGetFoundation().getAllocatorCallback())
Preprocessor macro for RepX serializer creation.
Function Documentation
template<typename TDataType > PX_INLINE PxRepXObject createRepXObject (const TDataType * inType, const PxSerialObjectId inId)
Inline helper template function to create PxRepXObject from TDataType type supporting PxTypeInfo<TDataType>::name.
Referenced by createRepXObject().
PX_INLINE PxRepXObject createRepXObject (const PxBase * inType, const PxSerialObjectId inId)
Inline helper function to create PxRepXObject from a PxBase instance.
References PxBase::getConcreteTypeName(), and PX_ASSERT.
template<typename TDataType > PX_INLINE PxRepXObject createRepXObject (const TDataType * inType)
Inline helper template function to create PxRepXObject form TDataType type using inType pointer as a PxSerialObjectId id.
References createRepXObject().
Copyright © 2008-2015 NVIDIA Corporation, 2701 San Tomas Expressway, Santa Clara, CA 95050 U.S.A. All rights reserved. www.nvidia.com