# Makefile generated by XPJ for android16
-include Makefile.custom
ProjectName = SnippetProfileZone
SnippetProfileZone_cppfiles   += ./../../SnippetCommon/ClassicMain.cpp
SnippetProfileZone_cppfiles   += ./../../SnippetProfileZone/SnippetProfileZone.cpp

SnippetProfileZone_cpp_debug_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_debug_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_debug_dep      = $(SnippetProfileZone_cpp_debug_dep) $(SnippetProfileZone_cc_debug_dep) $(SnippetProfileZone_c_debug_dep)
-include $(SnippetProfileZone_debug_dep)
SnippetProfileZone_cpp_checked_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_checked_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_checked_dep      = $(SnippetProfileZone_cpp_checked_dep) $(SnippetProfileZone_cc_checked_dep) $(SnippetProfileZone_c_checked_dep)
-include $(SnippetProfileZone_checked_dep)
SnippetProfileZone_cpp_profile_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_profile_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_profile_dep      = $(SnippetProfileZone_cpp_profile_dep) $(SnippetProfileZone_cc_profile_dep) $(SnippetProfileZone_c_profile_dep)
-include $(SnippetProfileZone_profile_dep)
SnippetProfileZone_cpp_release_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_release_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_release_dep      = $(SnippetProfileZone_cpp_release_dep) $(SnippetProfileZone_cc_release_dep) $(SnippetProfileZone_c_release_dep)
-include $(SnippetProfileZone_release_dep)
SnippetProfileZone_debug_hpaths    := 
SnippetProfileZone_debug_hpaths    += ./../../../Include
SnippetProfileZone_debug_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetProfileZone_debug_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetProfileZone_debug_lpaths    := 
SnippetProfileZone_debug_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetProfileZone_debug_lpaths    += ./../../../Lib/android16
SnippetProfileZone_debug_lpaths    += ./../../lib/android16
SnippetProfileZone_debug_lpaths    += ./../../lib/android16
SnippetProfileZone_debug_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_debug_defines   += ANDROID
SnippetProfileZone_debug_defines   += GLES2
SnippetProfileZone_debug_defines   += __ARM_ARCH_5__
SnippetProfileZone_debug_defines   += __ARM_ARCH_5T__
SnippetProfileZone_debug_defines   += __ARM_ARCH_5E__
SnippetProfileZone_debug_defines   += __ARM_ARCH_5TE__
SnippetProfileZone_debug_defines   += _DEBUG
SnippetProfileZone_debug_defines   += PX_DEBUG
SnippetProfileZone_debug_defines   += PX_CHECKED
SnippetProfileZone_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetProfileZone_debug_defines   += PX_NVTX
SnippetProfileZone_debug_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_debug_libraries := 
SnippetProfileZone_debug_libraries += SnippetUtilsDEBUG
SnippetProfileZone_debug_libraries += log
SnippetProfileZone_debug_libraries += gnustl_static
SnippetProfileZone_debug_libraries += supc++
SnippetProfileZone_debug_libraries += m
SnippetProfileZone_debug_libraries += c
SnippetProfileZone_debug_libraries += nvToolsExt
SnippetProfileZone_debug_libraries += PhysX3CommonDEBUG
SnippetProfileZone_debug_libraries += PhysX3DEBUG
SnippetProfileZone_debug_libraries += PhysX3VehicleDEBUG
SnippetProfileZone_debug_libraries += PhysX3CookingDEBUG
SnippetProfileZone_debug_libraries += PhysX3ExtensionsDEBUG
SnippetProfileZone_debug_libraries += PhysX3CharacterKinematicDEBUG
SnippetProfileZone_debug_libraries += SnippetUtilsDEBUG
SnippetProfileZone_debug_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_debug_common_cflags    += -MMD
SnippetProfileZone_debug_common_cflags    += $(addprefix -D, $(SnippetProfileZone_debug_defines))
SnippetProfileZone_debug_common_cflags    += $(addprefix -I, $(SnippetProfileZone_debug_hpaths))
SnippetProfileZone_debug_common_cflags  += -Werror
SnippetProfileZone_debug_common_cflags  += -fpic -fno-exceptions
SnippetProfileZone_debug_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_debug_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetProfileZone_debug_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetProfileZone_debug_common_cflags  += -Wno-long-long
SnippetProfileZone_debug_common_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-maybe-uninitialized
SnippetProfileZone_debug_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_debug_common_cflags  += -Wno-pedantic
SnippetProfileZone_debug_common_cflags  += -g3 -gdwarf-2
SnippetProfileZone_debug_cflags	:= $(SnippetProfileZone_debug_common_cflags)
SnippetProfileZone_debug_cppflags	:= $(SnippetProfileZone_debug_common_cflags)
SnippetProfileZone_debug_cppflags  += -fno-rtti
SnippetProfileZone_debug_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_debug_lflags    += $(addprefix -L, $(SnippetProfileZone_debug_lpaths))
SnippetProfileZone_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_debug_libraries)) -Wl,--end-group
SnippetProfileZone_debug_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_debug_lflags  += -Wl,--no-undefined
SnippetProfileZone_debug_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetProfileZone_debug_objsdir  = $(OBJS_DIR)/SnippetProfileZone_debug
SnippetProfileZone_debug_cpp_o    = $(addprefix $(SnippetProfileZone_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_debug_cc_o    = $(addprefix $(SnippetProfileZone_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_debug_c_o      = $(addprefix $(SnippetProfileZone_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_debug_obj      = $(SnippetProfileZone_debug_cpp_o) $(SnippetProfileZone_debug_cc_o) $(SnippetProfileZone_debug_c_o)
SnippetProfileZone_debug_bin      := ./../../../Bin/android16/SnippetProfileZoneDEBUG

clean_SnippetProfileZone_debug: 
	@$(ECHO) clean SnippetProfileZone debug
	@$(RMDIR) $(SnippetProfileZone_debug_objsdir)
	@$(RMDIR) $(SnippetProfileZone_debug_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/debug

build_SnippetProfileZone_debug: postbuild_SnippetProfileZone_debug
postbuild_SnippetProfileZone_debug: mainbuild_SnippetProfileZone_debug
mainbuild_SnippetProfileZone_debug: prebuild_SnippetProfileZone_debug $(SnippetProfileZone_debug_bin)
prebuild_SnippetProfileZone_debug:

$(SnippetProfileZone_debug_bin): $(SnippetProfileZone_debug_obj) build_SnippetUtils_debug 
	mkdir -p `dirname ./../../../Bin/android16/SnippetProfileZoneDEBUG`
	$(CCLD) $(SnippetProfileZone_debug_obj) $(SnippetProfileZone_debug_lflags) -o $(SnippetProfileZone_debug_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_debug_cpp_o): $(SnippetProfileZone_debug_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_debug_DEPDIR).d

$(SnippetProfileZone_debug_cc_o): $(SnippetProfileZone_debug_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).debug.P; \
	  rm -f $(SnippetProfileZone_debug_DEPDIR).d

$(SnippetProfileZone_debug_c_o): $(SnippetProfileZone_debug_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_debug_DEPDIR).d

SnippetProfileZone_checked_hpaths    := 
SnippetProfileZone_checked_hpaths    += ./../../../Include
SnippetProfileZone_checked_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetProfileZone_checked_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetProfileZone_checked_lpaths    := 
SnippetProfileZone_checked_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetProfileZone_checked_lpaths    += ./../../../Lib/android16
SnippetProfileZone_checked_lpaths    += ./../../lib/android16
SnippetProfileZone_checked_lpaths    += ./../../lib/android16
SnippetProfileZone_checked_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_checked_defines   += ANDROID
SnippetProfileZone_checked_defines   += GLES2
SnippetProfileZone_checked_defines   += __ARM_ARCH_5__
SnippetProfileZone_checked_defines   += __ARM_ARCH_5T__
SnippetProfileZone_checked_defines   += __ARM_ARCH_5E__
SnippetProfileZone_checked_defines   += __ARM_ARCH_5TE__
SnippetProfileZone_checked_defines   += NDEBUG
SnippetProfileZone_checked_defines   += PX_CHECKED
SnippetProfileZone_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetProfileZone_checked_defines   += PX_NVTX
SnippetProfileZone_checked_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_checked_libraries := 
SnippetProfileZone_checked_libraries += SnippetUtilsCHECKED
SnippetProfileZone_checked_libraries += log
SnippetProfileZone_checked_libraries += gnustl_static
SnippetProfileZone_checked_libraries += supc++
SnippetProfileZone_checked_libraries += m
SnippetProfileZone_checked_libraries += c
SnippetProfileZone_checked_libraries += nvToolsExt
SnippetProfileZone_checked_libraries += PhysX3CommonCHECKED
SnippetProfileZone_checked_libraries += PhysX3CHECKED
SnippetProfileZone_checked_libraries += PhysX3VehicleCHECKED
SnippetProfileZone_checked_libraries += PhysX3CookingCHECKED
SnippetProfileZone_checked_libraries += PhysX3ExtensionsCHECKED
SnippetProfileZone_checked_libraries += PhysX3CharacterKinematicCHECKED
SnippetProfileZone_checked_libraries += SnippetUtilsCHECKED
SnippetProfileZone_checked_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_checked_common_cflags    += -MMD
SnippetProfileZone_checked_common_cflags    += $(addprefix -D, $(SnippetProfileZone_checked_defines))
SnippetProfileZone_checked_common_cflags    += $(addprefix -I, $(SnippetProfileZone_checked_hpaths))
SnippetProfileZone_checked_common_cflags  += -Werror
SnippetProfileZone_checked_common_cflags  += -fpic -fno-exceptions
SnippetProfileZone_checked_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_checked_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetProfileZone_checked_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetProfileZone_checked_common_cflags  += -Wno-long-long
SnippetProfileZone_checked_common_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-maybe-uninitialized
SnippetProfileZone_checked_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_checked_common_cflags  += -Wno-pedantic
SnippetProfileZone_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetProfileZone_checked_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetProfileZone_checked_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetProfileZone_checked_cflags	:= $(SnippetProfileZone_checked_common_cflags)
SnippetProfileZone_checked_cppflags	:= $(SnippetProfileZone_checked_common_cflags)
SnippetProfileZone_checked_cppflags  += -fno-rtti
SnippetProfileZone_checked_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_checked_lflags    += $(addprefix -L, $(SnippetProfileZone_checked_lpaths))
SnippetProfileZone_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_checked_libraries)) -Wl,--end-group
SnippetProfileZone_checked_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_checked_lflags  += -Wl,--no-undefined
SnippetProfileZone_checked_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetProfileZone_checked_objsdir  = $(OBJS_DIR)/SnippetProfileZone_checked
SnippetProfileZone_checked_cpp_o    = $(addprefix $(SnippetProfileZone_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_checked_cc_o    = $(addprefix $(SnippetProfileZone_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_checked_c_o      = $(addprefix $(SnippetProfileZone_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_checked_obj      = $(SnippetProfileZone_checked_cpp_o) $(SnippetProfileZone_checked_cc_o) $(SnippetProfileZone_checked_c_o)
SnippetProfileZone_checked_bin      := ./../../../Bin/android16/SnippetProfileZoneCHECKED

clean_SnippetProfileZone_checked: 
	@$(ECHO) clean SnippetProfileZone checked
	@$(RMDIR) $(SnippetProfileZone_checked_objsdir)
	@$(RMDIR) $(SnippetProfileZone_checked_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/checked

build_SnippetProfileZone_checked: postbuild_SnippetProfileZone_checked
postbuild_SnippetProfileZone_checked: mainbuild_SnippetProfileZone_checked
mainbuild_SnippetProfileZone_checked: prebuild_SnippetProfileZone_checked $(SnippetProfileZone_checked_bin)
prebuild_SnippetProfileZone_checked:

$(SnippetProfileZone_checked_bin): $(SnippetProfileZone_checked_obj) build_SnippetUtils_checked 
	mkdir -p `dirname ./../../../Bin/android16/SnippetProfileZoneCHECKED`
	$(CCLD) $(SnippetProfileZone_checked_obj) $(SnippetProfileZone_checked_lflags) -o $(SnippetProfileZone_checked_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_checked_cpp_o): $(SnippetProfileZone_checked_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_checked_DEPDIR).d

$(SnippetProfileZone_checked_cc_o): $(SnippetProfileZone_checked_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).checked.P; \
	  rm -f $(SnippetProfileZone_checked_DEPDIR).d

$(SnippetProfileZone_checked_c_o): $(SnippetProfileZone_checked_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_checked_DEPDIR).d

SnippetProfileZone_profile_hpaths    := 
SnippetProfileZone_profile_hpaths    += ./../../../Include
SnippetProfileZone_profile_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetProfileZone_profile_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetProfileZone_profile_lpaths    := 
SnippetProfileZone_profile_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetProfileZone_profile_lpaths    += ./../../../Lib/android16
SnippetProfileZone_profile_lpaths    += ./../../lib/android16
SnippetProfileZone_profile_lpaths    += ./../../lib/android16
SnippetProfileZone_profile_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_profile_defines   += ANDROID
SnippetProfileZone_profile_defines   += GLES2
SnippetProfileZone_profile_defines   += __ARM_ARCH_5__
SnippetProfileZone_profile_defines   += __ARM_ARCH_5T__
SnippetProfileZone_profile_defines   += __ARM_ARCH_5E__
SnippetProfileZone_profile_defines   += __ARM_ARCH_5TE__
SnippetProfileZone_profile_defines   += NDEBUG
SnippetProfileZone_profile_defines   += PX_PROFILE
SnippetProfileZone_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetProfileZone_profile_defines   += PX_NVTX
SnippetProfileZone_profile_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_profile_libraries := 
SnippetProfileZone_profile_libraries += SnippetUtilsPROFILE
SnippetProfileZone_profile_libraries += log
SnippetProfileZone_profile_libraries += gnustl_static
SnippetProfileZone_profile_libraries += supc++
SnippetProfileZone_profile_libraries += m
SnippetProfileZone_profile_libraries += c
SnippetProfileZone_profile_libraries += nvToolsExt
SnippetProfileZone_profile_libraries += PhysX3CommonPROFILE
SnippetProfileZone_profile_libraries += PhysX3PROFILE
SnippetProfileZone_profile_libraries += PhysX3VehiclePROFILE
SnippetProfileZone_profile_libraries += PhysX3CookingPROFILE
SnippetProfileZone_profile_libraries += PhysX3ExtensionsPROFILE
SnippetProfileZone_profile_libraries += PhysX3CharacterKinematicPROFILE
SnippetProfileZone_profile_libraries += SnippetUtilsPROFILE
SnippetProfileZone_profile_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_profile_common_cflags    += -MMD
SnippetProfileZone_profile_common_cflags    += $(addprefix -D, $(SnippetProfileZone_profile_defines))
SnippetProfileZone_profile_common_cflags    += $(addprefix -I, $(SnippetProfileZone_profile_hpaths))
SnippetProfileZone_profile_common_cflags  += -Werror
SnippetProfileZone_profile_common_cflags  += -fpic -fno-exceptions
SnippetProfileZone_profile_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_profile_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetProfileZone_profile_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetProfileZone_profile_common_cflags  += -Wno-long-long
SnippetProfileZone_profile_common_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-maybe-uninitialized
SnippetProfileZone_profile_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_profile_common_cflags  += -Wno-pedantic
SnippetProfileZone_profile_common_cflags  += -O3 -fno-strict-aliasing
SnippetProfileZone_profile_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetProfileZone_profile_common_cflags  += -fno-omit-frame-pointer -funswitch-loops -finline-limit=300
SnippetProfileZone_profile_cflags	:= $(SnippetProfileZone_profile_common_cflags)
SnippetProfileZone_profile_cppflags	:= $(SnippetProfileZone_profile_common_cflags)
SnippetProfileZone_profile_cppflags  += -fno-rtti
SnippetProfileZone_profile_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_profile_lflags    += $(addprefix -L, $(SnippetProfileZone_profile_lpaths))
SnippetProfileZone_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_profile_libraries)) -Wl,--end-group
SnippetProfileZone_profile_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_profile_lflags  += -Wl,--no-undefined
SnippetProfileZone_profile_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetProfileZone_profile_objsdir  = $(OBJS_DIR)/SnippetProfileZone_profile
SnippetProfileZone_profile_cpp_o    = $(addprefix $(SnippetProfileZone_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_profile_cc_o    = $(addprefix $(SnippetProfileZone_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_profile_c_o      = $(addprefix $(SnippetProfileZone_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_profile_obj      = $(SnippetProfileZone_profile_cpp_o) $(SnippetProfileZone_profile_cc_o) $(SnippetProfileZone_profile_c_o)
SnippetProfileZone_profile_bin      := ./../../../Bin/android16/SnippetProfileZonePROFILE

clean_SnippetProfileZone_profile: 
	@$(ECHO) clean SnippetProfileZone profile
	@$(RMDIR) $(SnippetProfileZone_profile_objsdir)
	@$(RMDIR) $(SnippetProfileZone_profile_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/profile

build_SnippetProfileZone_profile: postbuild_SnippetProfileZone_profile
postbuild_SnippetProfileZone_profile: mainbuild_SnippetProfileZone_profile
mainbuild_SnippetProfileZone_profile: prebuild_SnippetProfileZone_profile $(SnippetProfileZone_profile_bin)
prebuild_SnippetProfileZone_profile:

$(SnippetProfileZone_profile_bin): $(SnippetProfileZone_profile_obj) build_SnippetUtils_profile 
	mkdir -p `dirname ./../../../Bin/android16/SnippetProfileZonePROFILE`
	$(CCLD) $(SnippetProfileZone_profile_obj) $(SnippetProfileZone_profile_lflags) -o $(SnippetProfileZone_profile_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_profile_cpp_o): $(SnippetProfileZone_profile_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_profile_DEPDIR).d

$(SnippetProfileZone_profile_cc_o): $(SnippetProfileZone_profile_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).profile.P; \
	  rm -f $(SnippetProfileZone_profile_DEPDIR).d

$(SnippetProfileZone_profile_c_o): $(SnippetProfileZone_profile_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_profile_DEPDIR).d

SnippetProfileZone_release_hpaths    := 
SnippetProfileZone_release_hpaths    += ./../../../Include
SnippetProfileZone_release_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/include
SnippetProfileZone_release_hpaths    += ./../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a/include
SnippetProfileZone_release_lpaths    := 
SnippetProfileZone_release_lpaths    += ./../../../externals/nvToolsExt/1/lib/armv7
SnippetProfileZone_release_lpaths    += ./../../../Lib/android16
SnippetProfileZone_release_lpaths    += ./../../lib/android16
SnippetProfileZone_release_lpaths    += ./../../lib/android16
SnippetProfileZone_release_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_release_defines   += ANDROID
SnippetProfileZone_release_defines   += GLES2
SnippetProfileZone_release_defines   += __ARM_ARCH_5__
SnippetProfileZone_release_defines   += __ARM_ARCH_5T__
SnippetProfileZone_release_defines   += __ARM_ARCH_5E__
SnippetProfileZone_release_defines   += __ARM_ARCH_5TE__
SnippetProfileZone_release_defines   += NDEBUG
SnippetProfileZone_release_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_release_libraries := 
SnippetProfileZone_release_libraries += SnippetUtils
SnippetProfileZone_release_libraries += log
SnippetProfileZone_release_libraries += gnustl_static
SnippetProfileZone_release_libraries += supc++
SnippetProfileZone_release_libraries += m
SnippetProfileZone_release_libraries += c
SnippetProfileZone_release_libraries += nvToolsExt
SnippetProfileZone_release_libraries += PhysX3Common
SnippetProfileZone_release_libraries += PhysX3
SnippetProfileZone_release_libraries += PhysX3Vehicle
SnippetProfileZone_release_libraries += PhysX3Cooking
SnippetProfileZone_release_libraries += PhysX3Extensions
SnippetProfileZone_release_libraries += PhysX3CharacterKinematic
SnippetProfileZone_release_libraries += SnippetUtils
SnippetProfileZone_release_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_release_common_cflags    += -MMD
SnippetProfileZone_release_common_cflags    += $(addprefix -D, $(SnippetProfileZone_release_defines))
SnippetProfileZone_release_common_cflags    += $(addprefix -I, $(SnippetProfileZone_release_hpaths))
SnippetProfileZone_release_common_cflags  += -Werror
SnippetProfileZone_release_common_cflags  += -fpic -fno-exceptions
SnippetProfileZone_release_common_cflags  += -isysroot ../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_release_common_cflags  += -march=armv7-a -mfpu=neon -marm -mfloat-abi=softfp -mthumb-interwork
SnippetProfileZone_release_common_cflags  += -Wall -Wextra -Wpedantic -Wstrict-aliasing=2
SnippetProfileZone_release_common_cflags  += -Wno-long-long
SnippetProfileZone_release_common_cflags  += -Wno-invalid-offsetof -Wno-unknown-pragmas -Wno-maybe-uninitialized
SnippetProfileZone_release_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_release_common_cflags  += -Wno-pedantic
SnippetProfileZone_release_common_cflags  += -O3 -fno-strict-aliasing
SnippetProfileZone_release_common_cflags  += -ffunction-sections -funwind-tables -fstack-protector
SnippetProfileZone_release_common_cflags  += -fomit-frame-pointer -funswitch-loops -finline-limit=300
SnippetProfileZone_release_cflags	:= $(SnippetProfileZone_release_common_cflags)
SnippetProfileZone_release_cppflags	:= $(SnippetProfileZone_release_common_cflags)
SnippetProfileZone_release_cppflags  += -fno-rtti
SnippetProfileZone_release_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_release_lflags    += $(addprefix -L, $(SnippetProfileZone_release_lpaths))
SnippetProfileZone_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_release_libraries)) -Wl,--end-group
SnippetProfileZone_release_lflags  += --sysroot=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm
SnippetProfileZone_release_lflags  += -Wl,--no-undefined
SnippetProfileZone_release_lflags  += -Wl,-z,noexecstack -L../../../externals/android-ndk-r9d/sources/cxx-stl/gnu-libstdc++/4.8/libs/armeabi-v7a -Wl,-rpath-link=../../../externals/android-ndk-r9d/platforms/android-16/arch-arm/usr/lib
SnippetProfileZone_release_objsdir  = $(OBJS_DIR)/SnippetProfileZone_release
SnippetProfileZone_release_cpp_o    = $(addprefix $(SnippetProfileZone_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_release_cc_o    = $(addprefix $(SnippetProfileZone_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_release_c_o      = $(addprefix $(SnippetProfileZone_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_release_obj      = $(SnippetProfileZone_release_cpp_o) $(SnippetProfileZone_release_cc_o) $(SnippetProfileZone_release_c_o)
SnippetProfileZone_release_bin      := ./../../../Bin/android16/SnippetProfileZone

clean_SnippetProfileZone_release: 
	@$(ECHO) clean SnippetProfileZone release
	@$(RMDIR) $(SnippetProfileZone_release_objsdir)
	@$(RMDIR) $(SnippetProfileZone_release_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/release

build_SnippetProfileZone_release: postbuild_SnippetProfileZone_release
postbuild_SnippetProfileZone_release: mainbuild_SnippetProfileZone_release
mainbuild_SnippetProfileZone_release: prebuild_SnippetProfileZone_release $(SnippetProfileZone_release_bin)
prebuild_SnippetProfileZone_release:

$(SnippetProfileZone_release_bin): $(SnippetProfileZone_release_obj) build_SnippetUtils_release 
	mkdir -p `dirname ./../../../Bin/android16/SnippetProfileZone`
	$(CCLD) $(SnippetProfileZone_release_obj) $(SnippetProfileZone_release_lflags) -o $(SnippetProfileZone_release_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_release_cpp_o): $(SnippetProfileZone_release_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_release_DEPDIR).d

$(SnippetProfileZone_release_cc_o): $(SnippetProfileZone_release_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).release.P; \
	  rm -f $(SnippetProfileZone_release_DEPDIR).d

$(SnippetProfileZone_release_c_o): $(SnippetProfileZone_release_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_release_DEPDIR).d

clean_SnippetProfileZone:  clean_SnippetProfileZone_debug clean_SnippetProfileZone_checked clean_SnippetProfileZone_profile clean_SnippetProfileZone_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
