# Makefile generated by XPJ for linux32
-include Makefile.custom
ProjectName = SnippetProfileZone
SnippetProfileZone_cppfiles   += ./../../SnippetCommon/ClassicMain.cpp
SnippetProfileZone_cppfiles   += ./../../SnippetProfileZone/SnippetProfileZone.cpp

SnippetProfileZone_cpp_debug_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_debug_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.debug.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_debug_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_debug_dep      = $(SnippetProfileZone_cpp_debug_dep) $(SnippetProfileZone_cc_debug_dep) $(SnippetProfileZone_c_debug_dep)
-include $(SnippetProfileZone_debug_dep)
SnippetProfileZone_cpp_checked_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_checked_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.checked.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_checked_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_checked_dep      = $(SnippetProfileZone_cpp_checked_dep) $(SnippetProfileZone_cc_checked_dep) $(SnippetProfileZone_c_checked_dep)
-include $(SnippetProfileZone_checked_dep)
SnippetProfileZone_cpp_profile_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_profile_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.profile.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_profile_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_profile_dep      = $(SnippetProfileZone_cpp_profile_dep) $(SnippetProfileZone_cc_profile_dep) $(SnippetProfileZone_c_profile_dep)
-include $(SnippetProfileZone_profile_dep)
SnippetProfileZone_cpp_release_dep    = $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.P, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_cc_release_dep    = $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.release.P, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_c_release_dep      = $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.P, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_release_dep      = $(SnippetProfileZone_cpp_release_dep) $(SnippetProfileZone_cc_release_dep) $(SnippetProfileZone_c_release_dep)
-include $(SnippetProfileZone_release_dep)
SnippetProfileZone_debug_hpaths    := 
SnippetProfileZone_debug_hpaths    += ./../../../Include
SnippetProfileZone_debug_lpaths    := 
SnippetProfileZone_debug_lpaths    += ./../../../Lib/linux32
SnippetProfileZone_debug_lpaths    += ./../../lib/linux32
SnippetProfileZone_debug_lpaths    += ./../../../Bin/linux32
SnippetProfileZone_debug_lpaths    += ./../../lib/linux32
SnippetProfileZone_debug_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_debug_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_debug_defines   += RENDER_SNIPPET
SnippetProfileZone_debug_defines   += _DEBUG
SnippetProfileZone_debug_defines   += PX_DEBUG
SnippetProfileZone_debug_defines   += PX_CHECKED
SnippetProfileZone_debug_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetProfileZone_debug_libraries := 
SnippetProfileZone_debug_libraries += SnippetRenderDEBUG
SnippetProfileZone_debug_libraries += SnippetUtilsDEBUG
SnippetProfileZone_debug_libraries += PhysX3DEBUG_x86
SnippetProfileZone_debug_libraries += PhysX3CommonDEBUG_x86
SnippetProfileZone_debug_libraries += PhysX3CookingDEBUG_x86
SnippetProfileZone_debug_libraries += PhysX3CharacterKinematicDEBUG_x86
SnippetProfileZone_debug_libraries += PhysX3ExtensionsDEBUG
SnippetProfileZone_debug_libraries += PhysX3VehicleDEBUG
SnippetProfileZone_debug_libraries += PhysXProfileSDKDEBUG
SnippetProfileZone_debug_libraries += PhysXVisualDebuggerSDKDEBUG
SnippetProfileZone_debug_libraries += PxTaskDEBUG
SnippetProfileZone_debug_libraries += SnippetUtilsDEBUG
SnippetProfileZone_debug_libraries += SnippetRenderDEBUG
SnippetProfileZone_debug_libraries += GL
SnippetProfileZone_debug_libraries += GLU
SnippetProfileZone_debug_libraries += glut
SnippetProfileZone_debug_libraries += X11
SnippetProfileZone_debug_libraries += rt
SnippetProfileZone_debug_libraries += pthread
SnippetProfileZone_debug_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_debug_common_cflags    += -MMD
SnippetProfileZone_debug_common_cflags    += $(addprefix -D, $(SnippetProfileZone_debug_defines))
SnippetProfileZone_debug_common_cflags    += $(addprefix -I, $(SnippetProfileZone_debug_hpaths))
SnippetProfileZone_debug_common_cflags  += -m32
SnippetProfileZone_debug_common_cflags  += -Werror -m32 -fPIC -msse2 -mfpmath=sse -malign-double -ffast-math -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetProfileZone_debug_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetProfileZone_debug_common_cflags  += -Wno-long-long
SnippetProfileZone_debug_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized
SnippetProfileZone_debug_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_debug_common_cflags  += -g3 -gdwarf-2
SnippetProfileZone_debug_cflags	:= $(SnippetProfileZone_debug_common_cflags)
SnippetProfileZone_debug_cppflags	:= $(SnippetProfileZone_debug_common_cflags)
SnippetProfileZone_debug_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_debug_lflags    += $(addprefix -L, $(SnippetProfileZone_debug_lpaths))
SnippetProfileZone_debug_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_debug_libraries)) -Wl,--end-group
SnippetProfileZone_debug_lflags  += -lrt
SnippetProfileZone_debug_lflags  += -Wl,-rpath ./
SnippetProfileZone_debug_lflags  += -m32
SnippetProfileZone_debug_objsdir  = $(OBJS_DIR)/SnippetProfileZone_debug
SnippetProfileZone_debug_cpp_o    = $(addprefix $(SnippetProfileZone_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_debug_cc_o    = $(addprefix $(SnippetProfileZone_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_debug_c_o      = $(addprefix $(SnippetProfileZone_debug_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_debug_obj      = $(SnippetProfileZone_debug_cpp_o) $(SnippetProfileZone_debug_cc_o) $(SnippetProfileZone_debug_c_o)
SnippetProfileZone_debug_bin      := ./../../../Bin/linux32/SnippetProfileZoneDEBUG

clean_SnippetProfileZone_debug: 
	@$(ECHO) clean SnippetProfileZone debug
	@$(RMDIR) $(SnippetProfileZone_debug_objsdir)
	@$(RMDIR) $(SnippetProfileZone_debug_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/debug

build_SnippetProfileZone_debug: postbuild_SnippetProfileZone_debug
postbuild_SnippetProfileZone_debug: mainbuild_SnippetProfileZone_debug
mainbuild_SnippetProfileZone_debug: prebuild_SnippetProfileZone_debug $(SnippetProfileZone_debug_bin)
prebuild_SnippetProfileZone_debug:

$(SnippetProfileZone_debug_bin): $(SnippetProfileZone_debug_obj) build_SnippetRender_debug build_SnippetUtils_debug 
	mkdir -p `dirname ./../../../Bin/linux32/SnippetProfileZoneDEBUG`
	$(CCLD) $(SnippetProfileZone_debug_obj) $(SnippetProfileZone_debug_lflags) -o $(SnippetProfileZone_debug_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_debug_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_debug_cpp_o): $(SnippetProfileZone_debug_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling debug $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_debug_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_debug_DEPDIR).d

$(SnippetProfileZone_debug_cc_o): $(SnippetProfileZone_debug_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling debug $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_debug_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_debug_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).debug.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).debug.P; \
	  rm -f $(SnippetProfileZone_debug_DEPDIR).d

$(SnippetProfileZone_debug_c_o): $(SnippetProfileZone_debug_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling debug $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_debug_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_debug_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_debug_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/debug/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_debug_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_debug_DEPDIR).d

SnippetProfileZone_checked_hpaths    := 
SnippetProfileZone_checked_hpaths    += ./../../../Include
SnippetProfileZone_checked_lpaths    := 
SnippetProfileZone_checked_lpaths    += ./../../../Lib/linux32
SnippetProfileZone_checked_lpaths    += ./../../lib/linux32
SnippetProfileZone_checked_lpaths    += ./../../../Bin/linux32
SnippetProfileZone_checked_lpaths    += ./../../lib/linux32
SnippetProfileZone_checked_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_checked_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_checked_defines   += RENDER_SNIPPET
SnippetProfileZone_checked_defines   += NDEBUG
SnippetProfileZone_checked_defines   += PX_CHECKED
SnippetProfileZone_checked_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetProfileZone_checked_libraries := 
SnippetProfileZone_checked_libraries += SnippetRenderCHECKED
SnippetProfileZone_checked_libraries += SnippetUtilsCHECKED
SnippetProfileZone_checked_libraries += PhysX3CHECKED_x86
SnippetProfileZone_checked_libraries += PhysX3CommonCHECKED_x86
SnippetProfileZone_checked_libraries += PhysX3CookingCHECKED_x86
SnippetProfileZone_checked_libraries += PhysX3CharacterKinematicCHECKED_x86
SnippetProfileZone_checked_libraries += PhysX3ExtensionsCHECKED
SnippetProfileZone_checked_libraries += PhysX3VehicleCHECKED
SnippetProfileZone_checked_libraries += PhysXProfileSDKCHECKED
SnippetProfileZone_checked_libraries += PhysXVisualDebuggerSDKCHECKED
SnippetProfileZone_checked_libraries += PxTaskCHECKED
SnippetProfileZone_checked_libraries += SnippetUtilsCHECKED
SnippetProfileZone_checked_libraries += SnippetRenderCHECKED
SnippetProfileZone_checked_libraries += GL
SnippetProfileZone_checked_libraries += GLU
SnippetProfileZone_checked_libraries += glut
SnippetProfileZone_checked_libraries += X11
SnippetProfileZone_checked_libraries += rt
SnippetProfileZone_checked_libraries += pthread
SnippetProfileZone_checked_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_checked_common_cflags    += -MMD
SnippetProfileZone_checked_common_cflags    += $(addprefix -D, $(SnippetProfileZone_checked_defines))
SnippetProfileZone_checked_common_cflags    += $(addprefix -I, $(SnippetProfileZone_checked_hpaths))
SnippetProfileZone_checked_common_cflags  += -m32
SnippetProfileZone_checked_common_cflags  += -Werror -m32 -fPIC -msse2 -mfpmath=sse -malign-double -ffast-math -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetProfileZone_checked_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetProfileZone_checked_common_cflags  += -Wno-long-long
SnippetProfileZone_checked_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized
SnippetProfileZone_checked_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_checked_common_cflags  += -g3 -gdwarf-2 -O3 -fno-strict-aliasing
SnippetProfileZone_checked_cflags	:= $(SnippetProfileZone_checked_common_cflags)
SnippetProfileZone_checked_cppflags	:= $(SnippetProfileZone_checked_common_cflags)
SnippetProfileZone_checked_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_checked_lflags    += $(addprefix -L, $(SnippetProfileZone_checked_lpaths))
SnippetProfileZone_checked_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_checked_libraries)) -Wl,--end-group
SnippetProfileZone_checked_lflags  += -lrt
SnippetProfileZone_checked_lflags  += -Wl,-rpath ./
SnippetProfileZone_checked_lflags  += -m32
SnippetProfileZone_checked_objsdir  = $(OBJS_DIR)/SnippetProfileZone_checked
SnippetProfileZone_checked_cpp_o    = $(addprefix $(SnippetProfileZone_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_checked_cc_o    = $(addprefix $(SnippetProfileZone_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_checked_c_o      = $(addprefix $(SnippetProfileZone_checked_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_checked_obj      = $(SnippetProfileZone_checked_cpp_o) $(SnippetProfileZone_checked_cc_o) $(SnippetProfileZone_checked_c_o)
SnippetProfileZone_checked_bin      := ./../../../Bin/linux32/SnippetProfileZoneCHECKED

clean_SnippetProfileZone_checked: 
	@$(ECHO) clean SnippetProfileZone checked
	@$(RMDIR) $(SnippetProfileZone_checked_objsdir)
	@$(RMDIR) $(SnippetProfileZone_checked_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/checked

build_SnippetProfileZone_checked: postbuild_SnippetProfileZone_checked
postbuild_SnippetProfileZone_checked: mainbuild_SnippetProfileZone_checked
mainbuild_SnippetProfileZone_checked: prebuild_SnippetProfileZone_checked $(SnippetProfileZone_checked_bin)
prebuild_SnippetProfileZone_checked:

$(SnippetProfileZone_checked_bin): $(SnippetProfileZone_checked_obj) build_SnippetRender_checked build_SnippetUtils_checked 
	mkdir -p `dirname ./../../../Bin/linux32/SnippetProfileZoneCHECKED`
	$(CCLD) $(SnippetProfileZone_checked_obj) $(SnippetProfileZone_checked_lflags) -o $(SnippetProfileZone_checked_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_checked_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_checked_cpp_o): $(SnippetProfileZone_checked_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling checked $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_checked_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_checked_DEPDIR).d

$(SnippetProfileZone_checked_cc_o): $(SnippetProfileZone_checked_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling checked $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_checked_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_checked_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).checked.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).checked.P; \
	  rm -f $(SnippetProfileZone_checked_DEPDIR).d

$(SnippetProfileZone_checked_c_o): $(SnippetProfileZone_checked_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling checked $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_checked_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_checked_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_checked_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/checked/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_checked_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_checked_DEPDIR).d

SnippetProfileZone_profile_hpaths    := 
SnippetProfileZone_profile_hpaths    += ./../../../Include
SnippetProfileZone_profile_lpaths    := 
SnippetProfileZone_profile_lpaths    += ./../../../Lib/linux32
SnippetProfileZone_profile_lpaths    += ./../../lib/linux32
SnippetProfileZone_profile_lpaths    += ./../../../Bin/linux32
SnippetProfileZone_profile_lpaths    += ./../../lib/linux32
SnippetProfileZone_profile_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_profile_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_profile_defines   += RENDER_SNIPPET
SnippetProfileZone_profile_defines   += NDEBUG
SnippetProfileZone_profile_defines   += PX_PROFILE
SnippetProfileZone_profile_defines   += PX_SUPPORT_VISUAL_DEBUGGER
SnippetProfileZone_profile_libraries := 
SnippetProfileZone_profile_libraries += SnippetRenderPROFILE
SnippetProfileZone_profile_libraries += SnippetUtilsPROFILE
SnippetProfileZone_profile_libraries += PhysX3PROFILE_x86
SnippetProfileZone_profile_libraries += PhysX3CommonPROFILE_x86
SnippetProfileZone_profile_libraries += PhysX3CookingPROFILE_x86
SnippetProfileZone_profile_libraries += PhysX3CharacterKinematicPROFILE_x86
SnippetProfileZone_profile_libraries += PhysX3ExtensionsPROFILE
SnippetProfileZone_profile_libraries += PhysX3VehiclePROFILE
SnippetProfileZone_profile_libraries += PhysXProfileSDKPROFILE
SnippetProfileZone_profile_libraries += PhysXVisualDebuggerSDKPROFILE
SnippetProfileZone_profile_libraries += PxTaskPROFILE
SnippetProfileZone_profile_libraries += SnippetUtilsPROFILE
SnippetProfileZone_profile_libraries += SnippetRenderPROFILE
SnippetProfileZone_profile_libraries += GL
SnippetProfileZone_profile_libraries += GLU
SnippetProfileZone_profile_libraries += glut
SnippetProfileZone_profile_libraries += X11
SnippetProfileZone_profile_libraries += rt
SnippetProfileZone_profile_libraries += pthread
SnippetProfileZone_profile_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_profile_common_cflags    += -MMD
SnippetProfileZone_profile_common_cflags    += $(addprefix -D, $(SnippetProfileZone_profile_defines))
SnippetProfileZone_profile_common_cflags    += $(addprefix -I, $(SnippetProfileZone_profile_hpaths))
SnippetProfileZone_profile_common_cflags  += -m32
SnippetProfileZone_profile_common_cflags  += -Werror -m32 -fPIC -msse2 -mfpmath=sse -malign-double -ffast-math -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetProfileZone_profile_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetProfileZone_profile_common_cflags  += -Wno-long-long
SnippetProfileZone_profile_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized
SnippetProfileZone_profile_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_profile_common_cflags  += -O3 -fno-strict-aliasing
SnippetProfileZone_profile_cflags	:= $(SnippetProfileZone_profile_common_cflags)
SnippetProfileZone_profile_cppflags	:= $(SnippetProfileZone_profile_common_cflags)
SnippetProfileZone_profile_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_profile_lflags    += $(addprefix -L, $(SnippetProfileZone_profile_lpaths))
SnippetProfileZone_profile_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_profile_libraries)) -Wl,--end-group
SnippetProfileZone_profile_lflags  += -lrt
SnippetProfileZone_profile_lflags  += -Wl,-rpath ./
SnippetProfileZone_profile_lflags  += -m32
SnippetProfileZone_profile_objsdir  = $(OBJS_DIR)/SnippetProfileZone_profile
SnippetProfileZone_profile_cpp_o    = $(addprefix $(SnippetProfileZone_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_profile_cc_o    = $(addprefix $(SnippetProfileZone_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_profile_c_o      = $(addprefix $(SnippetProfileZone_profile_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_profile_obj      = $(SnippetProfileZone_profile_cpp_o) $(SnippetProfileZone_profile_cc_o) $(SnippetProfileZone_profile_c_o)
SnippetProfileZone_profile_bin      := ./../../../Bin/linux32/SnippetProfileZonePROFILE

clean_SnippetProfileZone_profile: 
	@$(ECHO) clean SnippetProfileZone profile
	@$(RMDIR) $(SnippetProfileZone_profile_objsdir)
	@$(RMDIR) $(SnippetProfileZone_profile_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/profile

build_SnippetProfileZone_profile: postbuild_SnippetProfileZone_profile
postbuild_SnippetProfileZone_profile: mainbuild_SnippetProfileZone_profile
mainbuild_SnippetProfileZone_profile: prebuild_SnippetProfileZone_profile $(SnippetProfileZone_profile_bin)
prebuild_SnippetProfileZone_profile:

$(SnippetProfileZone_profile_bin): $(SnippetProfileZone_profile_obj) build_SnippetRender_profile build_SnippetUtils_profile 
	mkdir -p `dirname ./../../../Bin/linux32/SnippetProfileZonePROFILE`
	$(CCLD) $(SnippetProfileZone_profile_obj) $(SnippetProfileZone_profile_lflags) -o $(SnippetProfileZone_profile_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_profile_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_profile_cpp_o): $(SnippetProfileZone_profile_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling profile $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_profile_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_profile_DEPDIR).d

$(SnippetProfileZone_profile_cc_o): $(SnippetProfileZone_profile_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling profile $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_profile_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_profile_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).profile.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).profile.P; \
	  rm -f $(SnippetProfileZone_profile_DEPDIR).d

$(SnippetProfileZone_profile_c_o): $(SnippetProfileZone_profile_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling profile $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_profile_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_profile_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_profile_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/profile/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_profile_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_profile_DEPDIR).d

SnippetProfileZone_release_hpaths    := 
SnippetProfileZone_release_hpaths    += ./../../../Include
SnippetProfileZone_release_lpaths    := 
SnippetProfileZone_release_lpaths    += ./../../../Lib/linux32
SnippetProfileZone_release_lpaths    += ./../../lib/linux32
SnippetProfileZone_release_lpaths    += ./../../../Bin/linux32
SnippetProfileZone_release_lpaths    += ./../../lib/linux32
SnippetProfileZone_release_defines   := $(SnippetProfileZone_custom_defines)
SnippetProfileZone_release_defines   += PHYSX_PROFILE_SDK
SnippetProfileZone_release_defines   += RENDER_SNIPPET
SnippetProfileZone_release_defines   += NDEBUG
SnippetProfileZone_release_libraries := 
SnippetProfileZone_release_libraries += SnippetRender
SnippetProfileZone_release_libraries += SnippetUtils
SnippetProfileZone_release_libraries += PhysX3_x86
SnippetProfileZone_release_libraries += PhysX3Common_x86
SnippetProfileZone_release_libraries += PhysX3Cooking_x86
SnippetProfileZone_release_libraries += PhysX3CharacterKinematic_x86
SnippetProfileZone_release_libraries += PhysX3Extensions
SnippetProfileZone_release_libraries += PhysX3Vehicle
SnippetProfileZone_release_libraries += PhysXProfileSDK
SnippetProfileZone_release_libraries += PhysXVisualDebuggerSDK
SnippetProfileZone_release_libraries += PxTask
SnippetProfileZone_release_libraries += SnippetUtils
SnippetProfileZone_release_libraries += SnippetRender
SnippetProfileZone_release_libraries += GL
SnippetProfileZone_release_libraries += GLU
SnippetProfileZone_release_libraries += glut
SnippetProfileZone_release_libraries += X11
SnippetProfileZone_release_libraries += rt
SnippetProfileZone_release_libraries += pthread
SnippetProfileZone_release_common_cflags	:= $(SnippetProfileZone_custom_cflags)
SnippetProfileZone_release_common_cflags    += -MMD
SnippetProfileZone_release_common_cflags    += $(addprefix -D, $(SnippetProfileZone_release_defines))
SnippetProfileZone_release_common_cflags    += $(addprefix -I, $(SnippetProfileZone_release_hpaths))
SnippetProfileZone_release_common_cflags  += -m32
SnippetProfileZone_release_common_cflags  += -Werror -m32 -fPIC -msse2 -mfpmath=sse -malign-double -ffast-math -fno-exceptions -fno-rtti -fvisibility=hidden -fvisibility-inlines-hidden
SnippetProfileZone_release_common_cflags  += -Wall -Wextra -Wstrict-aliasing=2 -fdiagnostics-show-option
SnippetProfileZone_release_common_cflags  += -Wno-long-long
SnippetProfileZone_release_common_cflags  += -Wno-unknown-pragmas -Wno-invalid-offsetof -Wno-uninitialized
SnippetProfileZone_release_common_cflags  += -Wno-unused-parameter
SnippetProfileZone_release_common_cflags  += -O3 -fno-strict-aliasing
SnippetProfileZone_release_cflags	:= $(SnippetProfileZone_release_common_cflags)
SnippetProfileZone_release_cppflags	:= $(SnippetProfileZone_release_common_cflags)
SnippetProfileZone_release_lflags    := $(SnippetProfileZone_custom_lflags)
SnippetProfileZone_release_lflags    += $(addprefix -L, $(SnippetProfileZone_release_lpaths))
SnippetProfileZone_release_lflags    += -Wl,--start-group $(addprefix -l, $(SnippetProfileZone_release_libraries)) -Wl,--end-group
SnippetProfileZone_release_lflags  += -lrt
SnippetProfileZone_release_lflags  += -Wl,-rpath ./
SnippetProfileZone_release_lflags  += -m32
SnippetProfileZone_release_objsdir  = $(OBJS_DIR)/SnippetProfileZone_release
SnippetProfileZone_release_cpp_o    = $(addprefix $(SnippetProfileZone_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cpp, %.cpp.o, $(SnippetProfileZone_cppfiles)))))
SnippetProfileZone_release_cc_o    = $(addprefix $(SnippetProfileZone_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.cc, %.cc.o, $(SnippetProfileZone_ccfiles)))))
SnippetProfileZone_release_c_o      = $(addprefix $(SnippetProfileZone_release_objsdir)/, $(subst ./, , $(subst ../, , $(patsubst %.c, %.c.o, $(SnippetProfileZone_cfiles)))))
SnippetProfileZone_release_obj      = $(SnippetProfileZone_release_cpp_o) $(SnippetProfileZone_release_cc_o) $(SnippetProfileZone_release_c_o)
SnippetProfileZone_release_bin      := ./../../../Bin/linux32/SnippetProfileZone

clean_SnippetProfileZone_release: 
	@$(ECHO) clean SnippetProfileZone release
	@$(RMDIR) $(SnippetProfileZone_release_objsdir)
	@$(RMDIR) $(SnippetProfileZone_release_bin)
	@$(RMDIR) $(DEPSDIR)/SnippetProfileZone/release

build_SnippetProfileZone_release: postbuild_SnippetProfileZone_release
postbuild_SnippetProfileZone_release: mainbuild_SnippetProfileZone_release
mainbuild_SnippetProfileZone_release: prebuild_SnippetProfileZone_release $(SnippetProfileZone_release_bin)
prebuild_SnippetProfileZone_release:

$(SnippetProfileZone_release_bin): $(SnippetProfileZone_release_obj) build_SnippetRender_release build_SnippetUtils_release 
	mkdir -p `dirname ./../../../Bin/linux32/SnippetProfileZone`
	$(CCLD) $(SnippetProfileZone_release_obj) $(SnippetProfileZone_release_lflags) -o $(SnippetProfileZone_release_bin) 
	$(ECHO) building $@ complete!

SnippetProfileZone_release_DEPDIR = $(dir $(@))/$(*F)
$(SnippetProfileZone_release_cpp_o): $(SnippetProfileZone_release_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling release $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_release_cppflags) -c $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles)) -o $@
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))))
	cp $(SnippetProfileZone_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cpp.o,.cpp, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cppfiles))))).P; \
	  rm -f $(SnippetProfileZone_release_DEPDIR).d

$(SnippetProfileZone_release_cc_o): $(SnippetProfileZone_release_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling release $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))...
	mkdir -p $(dir $(@))
	$(CXX) $(SnippetProfileZone_release_cppflags) -c $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles)) -o $@
	mkdir -p $(dir $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))))
	cp $(SnippetProfileZone_release_DEPDIR).d $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).release.P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .cc.o,.cc, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_ccfiles))))).release.P; \
	  rm -f $(SnippetProfileZone_release_DEPDIR).d

$(SnippetProfileZone_release_c_o): $(SnippetProfileZone_release_objsdir)/%.o:
	$(ECHO) SnippetProfileZone: compiling release $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))...
	mkdir -p $(dir $(@))
	$(CC) $(SnippetProfileZone_release_cflags) -c $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles)) -o $@ 
	@mkdir -p $(dir $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))))))
	cp $(SnippetProfileZone_release_DEPDIR).d $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  sed -e 's/#.*//' -e 's/^[^:]*: *//' -e 's/ *\\$$//' \
		-e '/^$$/ d' -e 's/$$/ :/' < $(SnippetProfileZone_release_DEPDIR).d >> $(addprefix $(DEPSDIR)/SnippetProfileZone/release/, $(subst ./, , $(subst ../, , $(filter %$(strip $(subst .c.o,.c, $(subst $(SnippetProfileZone_release_objsdir),, $@))), $(SnippetProfileZone_cfiles))))).P; \
	  rm -f $(SnippetProfileZone_release_DEPDIR).d

clean_SnippetProfileZone:  clean_SnippetProfileZone_debug clean_SnippetProfileZone_checked clean_SnippetProfileZone_profile clean_SnippetProfileZone_release
	rm -rf $(DEPSDIR)

export VERBOSE
ifndef VERBOSE
.SILENT:
endif
